$axure.loadCurrentPage({
  "url":"关注（我已付费）.html",
  "generationDate":new Date(1429020443003.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"05c596df778f4a298eb39705b0982bae",
    "type":"Axure:Page",
    "name":"关注（我已付费）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"56bfbb24bd264fb08d21bd38b149d8d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98dca66a93224e8999fe161e70512e63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u0.png"}},
{
          "id":"60237faf1b4a4fd2b75e03cda720da17",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":64},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"21da9c1fac3d45e685d8f5c40b800dbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":465},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8951ce84bd8e4ed183ccb87b56bc8a5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":465},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"da2b584541bc4b009962d38478a961a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f5547322d7a4ba7ba5589be5a7937e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"d4624f5d344046c5b33f7b0b2fc7cb88",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24dcfb73c01a4f7db223ccb85f629244",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"4e7f3fd926404c818c8afe76372e05cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa5a079311f14fac8ddc1088a5f6acf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"dd509e3ea3a647dbbe0de8de19021678",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":180,
              "y":32},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a613105a92644dfbdca593143016dfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":180,
                  "y":32},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb984fedadc24c16bb2e7a6f6fd61530",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":456},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"6d38088a57dc496ab786236a23d79811",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7a6e262ec73452b998ed56c185d96fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"f56b722b0fb24670b5b09a107ad08733",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":74},
            "size":{
              "width":300,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8266e6cbeef24969a1ea8f38fd0af8f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":74},
                "size":{
                  "width":300,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u16.png"}},
{
          "id":"c18c086107bc4d448a52bd36f9804619",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":74},
            "size":{
              "width":10,
              "height":26}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/关注/u18_line.png"}},
{
          "id":"dcea79e6853c422e8567241c6b411552",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":79},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e313dad403624d65be169fa2881dafd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":79},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"096e142359124551bb92b35dfc2afccb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":79},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75a8062420ac4bc7bdf776337a424370",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":237,
                  "y":79},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"656a2f49a720441cba7c73f89adf9a94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":456},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8dc11bcee7246c9bbcd6a0fde105397",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":201,
                  "y":456},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u23.png"}},
{
          "id":"8929c1de5fe44fb8b8af5d192683e913",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":120},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b880ea5e74247d1908e00ec5673c36d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":120},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注（我已付费）/u25.png"}},
{
          "id":"d8e0a5b6c0be484390baf441941ed908",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":125},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0449f42e6d24760a6034353e98f677d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":125},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fae4f078d4c54314b6450200164f451b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":147},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d0508d456ce49c881514ed6bf52f268",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":147},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57904d9fde8840b7914f0119a471e872",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":147},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96179bd48a45454bac28728f254a3408",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":147},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fe847ffe07f4038afda18bd8ba86848",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":186},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baf11ee828af4ada8b9530dbe4346012",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":186},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注（我已付费）/u25.png"}},
{
          "id":"58ae43cce6f241b5a1904eff8e41b37c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":191},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbc54648eed34f408100bd125e8f9e9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":191},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c511b1908444503a31fde4fc7c79066",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":213},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"270df934ec014bd8a71d34c9f58fb9da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":213},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24631c12ed994875bf29e634b246530d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":213},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34c4ce4f780c4012862ef1b12b538e98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":213},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33128947dcdb4a06a6fc79c3474a4d16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":250},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8b71f0fe89d474d8e2f66cd95a64a65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":250},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注（我已付费）/u25.png"}},
{
          "id":"6309665cfa864f37a61a98ee88475390",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":255},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65df77dc549742468a26ca9f25491ae8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":255},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4db86ff002e54ac4af36ab85de66d96d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":277},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b89fde3bd5db417c9e4ce324958504bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":277},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc8690c40ab04e8281907dc6af560a1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":277},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ca3d6971ec14625bc8825f14d5db89a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":277},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"892f36a7658b412cac60e9252dfbcd09",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":314},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b94986f2446c49749c6755b12934f654",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":314},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注（我已付费）/u25.png"}},
{
          "id":"52f6741fac40424ab1357b3c519d6865",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":319},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9970ef5248b74ea3b376ce4e8067860e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":319},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"995aef7e03164e65a53b56b3d805887b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":341},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d18942e9150e462bb4c95b210e9a3e63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":341},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cfa5421077f40a79de8fd3d7802f26f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":341},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24046f66b98140d59fd593a4bfc429a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":341},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec7eadc2a466456a81a36ef2aa1b3b20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":520},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d469a15b7166479d937848532d3687ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":520},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u0.png"}},
{
          "id":"3bd1149190aa413eb5bf5911a29cbdab",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":564},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"cafa862faac640019fed303e6ac828ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":966},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c145f99b42504cccb6aab43dd079d38d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":966},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"dd247a81c83045febe67e5707e0ef020",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":966},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"637a8ccddfa443a4aaa029308ade3380",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":966},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"6a57927ce2a2432e960c79bf3fdc1f1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":966},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0272eac897549e4901c9f1fb946e9b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":966},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"4fb255e751054d7cb02cd5992b8b4300",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":966},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f387833d82234e679eef13534281e5de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":966},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"72596f74a118462ea9e95702d5063887",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":180,
              "y":532},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e6f858a7e984ad999a93e422ed2c139",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":180,
                  "y":532},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e27047518f94e13b60d5a6d91c5ca8f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":956},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"46a4620374c14a59a787a6fb616c0861",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":966},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"565461ef316d4cd784bca6d4d6e14062",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":966},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"6851c355ff7f4723a666cd4612fc0f75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":574},
            "size":{
              "width":300,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5b354c83dcc49b7884a449b0acba733",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":574},
                "size":{
                  "width":300,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u16.png"}},
{
          "id":"8209c31134fd4cf68aad3e2e693db6b2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":574},
            "size":{
              "width":10,
              "height":26}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/关注/u18_line.png"}},
{
          "id":"bfe8dc6503df49ca9cc124109e6ce80b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":580},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6529c0578e664dca89f28eaefabba379",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":580},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae3049f2ed254f8ba459c163fb0e6e20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":580},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88768b5fd98a4be2add89111255f9332",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":237,
                  "y":580},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af3dc03ffe0d490aa1f56c12b2c62358",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":956},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39335d6c20364fa5bd7fc08cdff038fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":201,
                  "y":956},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u23.png"}},
{
          "id":"dcf1d986237d4f4a8f938c3f848be66b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":620},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3069d7759244dd48f9c3a650bc9a702",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":620},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注（我已付费）/u25.png"}},
{
          "id":"7ee23ef408394ef1896823cd686aee65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":626},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"713dad3ac2cd4691872b922e103e9e91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":626},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cdb5ab34c3c4e5a85dbd7e610621cba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":648},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40bf7722667742a0a6cfa7c32280eaab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":648},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb5a98fdbf8241179072bbf94fbd7faa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":648},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bef7be528f324f4db9f342036c8d2121",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":648},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1612494fe30f4a50a76be471a398d492",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":686},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1aed6ce6f7b412f880de20aa1f782f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":686},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注（我已付费）/u25.png"}},
{
          "id":"3f47f599429f4384b81044bfa2faeaae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":692},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9806bfd5f007448cac7f870020741190",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":692},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0868d966e254f0ab4ce02583db95839",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":714},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ee85787b3324151a85aacd7db87a79a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":714},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea34b0cd44d04d21a4c48699f0b9d1f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":714},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5b8bdfdae824a8b8ec9dcef5f920437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":714},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9d1a18c2f504584a4b5dceba60ea62d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":750},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8695372827d24f2494b1d772442a61a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":750},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注（我已付费）/u25.png"}},
{
          "id":"01944f3a8de74fb4a7fe4717436913f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":756},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f10eaa504f34062a6d60b70126d9dde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":756},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e121d123b5e24c2c9094fd1fe238b5e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":778},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be934ef2ec8a453aa386dcd9fdc417d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":778},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"055fa0c5263a46e7accc6b98a557e58e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":778},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f38bd829ce3f44c89ade867fd5bc2b6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":778},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6fd541ca6ae43fb8cd5ccfa4179e39a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":814},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b04bb078e6604934ab28a9515eb3713b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":814},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注（我已付费）/u25.png"}},
{
          "id":"4d35b74486cb49a79e689b4c53f32b77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":820},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"446aacef9fab4dca888ebbc8357885c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":820},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fccddb75a75144dd8964e73e72ef0161",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":842},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ee5e07712934bc091750873af90b62c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":842},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e1b4da90b6e447e93d074e980577bcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":842},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85441002e4cc4a31a99f96388dec3b74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":842},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a032a0b6899d4c66869b4b926f367218",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":155,
              "y":81},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5183dd646f44162a5cd5be45f5a227b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":155,
                  "y":81},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u120.png"}},
{
          "id":"c6f5d2b636a8456eaf97a495b3deb0e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":143,
              "y":464},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d54107db091b4fa19d9e779caea106c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":143,
                  "y":464},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u120.png"}},
{
          "id":"6930ef56dc3d4f44b960e28c4bf99ed9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":294,
              "y":582},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4471199f5e324058bad0cf95a0767fe2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":294,
                  "y":582},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u120.png"}},
{
          "id":"c8587cb9442f4494bd0757b7327c7a0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":148,
              "y":965},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8b72f697a514b14a2239c6a9e11056d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":148,
                  "y":965},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u120.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "56bfbb24bd264fb08d21bd38b149d8d8":{
      "scriptId":"u0"},
    "98dca66a93224e8999fe161e70512e63":{
      "scriptId":"u1"},
    "60237faf1b4a4fd2b75e03cda720da17":{
      "scriptId":"u2"},
    "21da9c1fac3d45e685d8f5c40b800dbd":{
      "scriptId":"u3"},
    "8951ce84bd8e4ed183ccb87b56bc8a5c":{
      "scriptId":"u4"},
    "da2b584541bc4b009962d38478a961a1":{
      "scriptId":"u5"},
    "9f5547322d7a4ba7ba5589be5a7937e6":{
      "scriptId":"u6"},
    "d4624f5d344046c5b33f7b0b2fc7cb88":{
      "scriptId":"u7"},
    "24dcfb73c01a4f7db223ccb85f629244":{
      "scriptId":"u8"},
    "4e7f3fd926404c818c8afe76372e05cf":{
      "scriptId":"u9"},
    "aa5a079311f14fac8ddc1088a5f6acf9":{
      "scriptId":"u10"},
    "dd509e3ea3a647dbbe0de8de19021678":{
      "scriptId":"u11"},
    "0a613105a92644dfbdca593143016dfc":{
      "scriptId":"u12"},
    "cb984fedadc24c16bb2e7a6f6fd61530":{
      "scriptId":"u13"},
    "6d38088a57dc496ab786236a23d79811":{
      "scriptId":"u14"},
    "b7a6e262ec73452b998ed56c185d96fc":{
      "scriptId":"u15"},
    "f56b722b0fb24670b5b09a107ad08733":{
      "scriptId":"u16"},
    "8266e6cbeef24969a1ea8f38fd0af8f0":{
      "scriptId":"u17"},
    "c18c086107bc4d448a52bd36f9804619":{
      "scriptId":"u18"},
    "dcea79e6853c422e8567241c6b411552":{
      "scriptId":"u19"},
    "e313dad403624d65be169fa2881dafd7":{
      "scriptId":"u20"},
    "096e142359124551bb92b35dfc2afccb":{
      "scriptId":"u21"},
    "75a8062420ac4bc7bdf776337a424370":{
      "scriptId":"u22"},
    "656a2f49a720441cba7c73f89adf9a94":{
      "scriptId":"u23"},
    "a8dc11bcee7246c9bbcd6a0fde105397":{
      "scriptId":"u24"},
    "8929c1de5fe44fb8b8af5d192683e913":{
      "scriptId":"u25"},
    "9b880ea5e74247d1908e00ec5673c36d":{
      "scriptId":"u26"},
    "d8e0a5b6c0be484390baf441941ed908":{
      "scriptId":"u27"},
    "e0449f42e6d24760a6034353e98f677d":{
      "scriptId":"u28"},
    "fae4f078d4c54314b6450200164f451b":{
      "scriptId":"u29"},
    "7d0508d456ce49c881514ed6bf52f268":{
      "scriptId":"u30"},
    "57904d9fde8840b7914f0119a471e872":{
      "scriptId":"u31"},
    "96179bd48a45454bac28728f254a3408":{
      "scriptId":"u32"},
    "1fe847ffe07f4038afda18bd8ba86848":{
      "scriptId":"u33"},
    "baf11ee828af4ada8b9530dbe4346012":{
      "scriptId":"u34"},
    "58ae43cce6f241b5a1904eff8e41b37c":{
      "scriptId":"u35"},
    "fbc54648eed34f408100bd125e8f9e9d":{
      "scriptId":"u36"},
    "3c511b1908444503a31fde4fc7c79066":{
      "scriptId":"u37"},
    "270df934ec014bd8a71d34c9f58fb9da":{
      "scriptId":"u38"},
    "24631c12ed994875bf29e634b246530d":{
      "scriptId":"u39"},
    "34c4ce4f780c4012862ef1b12b538e98":{
      "scriptId":"u40"},
    "33128947dcdb4a06a6fc79c3474a4d16":{
      "scriptId":"u41"},
    "e8b71f0fe89d474d8e2f66cd95a64a65":{
      "scriptId":"u42"},
    "6309665cfa864f37a61a98ee88475390":{
      "scriptId":"u43"},
    "65df77dc549742468a26ca9f25491ae8":{
      "scriptId":"u44"},
    "4db86ff002e54ac4af36ab85de66d96d":{
      "scriptId":"u45"},
    "b89fde3bd5db417c9e4ce324958504bc":{
      "scriptId":"u46"},
    "bc8690c40ab04e8281907dc6af560a1b":{
      "scriptId":"u47"},
    "7ca3d6971ec14625bc8825f14d5db89a":{
      "scriptId":"u48"},
    "892f36a7658b412cac60e9252dfbcd09":{
      "scriptId":"u49"},
    "b94986f2446c49749c6755b12934f654":{
      "scriptId":"u50"},
    "52f6741fac40424ab1357b3c519d6865":{
      "scriptId":"u51"},
    "9970ef5248b74ea3b376ce4e8067860e":{
      "scriptId":"u52"},
    "995aef7e03164e65a53b56b3d805887b":{
      "scriptId":"u53"},
    "d18942e9150e462bb4c95b210e9a3e63":{
      "scriptId":"u54"},
    "1cfa5421077f40a79de8fd3d7802f26f":{
      "scriptId":"u55"},
    "24046f66b98140d59fd593a4bfc429a7":{
      "scriptId":"u56"},
    "ec7eadc2a466456a81a36ef2aa1b3b20":{
      "scriptId":"u57"},
    "d469a15b7166479d937848532d3687ef":{
      "scriptId":"u58"},
    "3bd1149190aa413eb5bf5911a29cbdab":{
      "scriptId":"u59"},
    "cafa862faac640019fed303e6ac828ae":{
      "scriptId":"u60"},
    "c145f99b42504cccb6aab43dd079d38d":{
      "scriptId":"u61"},
    "dd247a81c83045febe67e5707e0ef020":{
      "scriptId":"u62"},
    "637a8ccddfa443a4aaa029308ade3380":{
      "scriptId":"u63"},
    "6a57927ce2a2432e960c79bf3fdc1f1f":{
      "scriptId":"u64"},
    "c0272eac897549e4901c9f1fb946e9b9":{
      "scriptId":"u65"},
    "4fb255e751054d7cb02cd5992b8b4300":{
      "scriptId":"u66"},
    "f387833d82234e679eef13534281e5de":{
      "scriptId":"u67"},
    "72596f74a118462ea9e95702d5063887":{
      "scriptId":"u68"},
    "6e6f858a7e984ad999a93e422ed2c139":{
      "scriptId":"u69"},
    "0e27047518f94e13b60d5a6d91c5ca8f":{
      "scriptId":"u70"},
    "46a4620374c14a59a787a6fb616c0861":{
      "scriptId":"u71"},
    "565461ef316d4cd784bca6d4d6e14062":{
      "scriptId":"u72"},
    "6851c355ff7f4723a666cd4612fc0f75":{
      "scriptId":"u73"},
    "b5b354c83dcc49b7884a449b0acba733":{
      "scriptId":"u74"},
    "8209c31134fd4cf68aad3e2e693db6b2":{
      "scriptId":"u75"},
    "bfe8dc6503df49ca9cc124109e6ce80b":{
      "scriptId":"u76"},
    "6529c0578e664dca89f28eaefabba379":{
      "scriptId":"u77"},
    "ae3049f2ed254f8ba459c163fb0e6e20":{
      "scriptId":"u78"},
    "88768b5fd98a4be2add89111255f9332":{
      "scriptId":"u79"},
    "af3dc03ffe0d490aa1f56c12b2c62358":{
      "scriptId":"u80"},
    "39335d6c20364fa5bd7fc08cdff038fe":{
      "scriptId":"u81"},
    "dcf1d986237d4f4a8f938c3f848be66b":{
      "scriptId":"u82"},
    "a3069d7759244dd48f9c3a650bc9a702":{
      "scriptId":"u83"},
    "7ee23ef408394ef1896823cd686aee65":{
      "scriptId":"u84"},
    "713dad3ac2cd4691872b922e103e9e91":{
      "scriptId":"u85"},
    "6cdb5ab34c3c4e5a85dbd7e610621cba":{
      "scriptId":"u86"},
    "40bf7722667742a0a6cfa7c32280eaab":{
      "scriptId":"u87"},
    "bb5a98fdbf8241179072bbf94fbd7faa":{
      "scriptId":"u88"},
    "bef7be528f324f4db9f342036c8d2121":{
      "scriptId":"u89"},
    "1612494fe30f4a50a76be471a398d492":{
      "scriptId":"u90"},
    "c1aed6ce6f7b412f880de20aa1f782f6":{
      "scriptId":"u91"},
    "3f47f599429f4384b81044bfa2faeaae":{
      "scriptId":"u92"},
    "9806bfd5f007448cac7f870020741190":{
      "scriptId":"u93"},
    "e0868d966e254f0ab4ce02583db95839":{
      "scriptId":"u94"},
    "9ee85787b3324151a85aacd7db87a79a":{
      "scriptId":"u95"},
    "ea34b0cd44d04d21a4c48699f0b9d1f3":{
      "scriptId":"u96"},
    "d5b8bdfdae824a8b8ec9dcef5f920437":{
      "scriptId":"u97"},
    "d9d1a18c2f504584a4b5dceba60ea62d":{
      "scriptId":"u98"},
    "8695372827d24f2494b1d772442a61a6":{
      "scriptId":"u99"},
    "01944f3a8de74fb4a7fe4717436913f2":{
      "scriptId":"u100"},
    "4f10eaa504f34062a6d60b70126d9dde":{
      "scriptId":"u101"},
    "e121d123b5e24c2c9094fd1fe238b5e8":{
      "scriptId":"u102"},
    "be934ef2ec8a453aa386dcd9fdc417d9":{
      "scriptId":"u103"},
    "055fa0c5263a46e7accc6b98a557e58e":{
      "scriptId":"u104"},
    "f38bd829ce3f44c89ade867fd5bc2b6e":{
      "scriptId":"u105"},
    "f6fd541ca6ae43fb8cd5ccfa4179e39a":{
      "scriptId":"u106"},
    "b04bb078e6604934ab28a9515eb3713b":{
      "scriptId":"u107"},
    "4d35b74486cb49a79e689b4c53f32b77":{
      "scriptId":"u108"},
    "446aacef9fab4dca888ebbc8357885c8":{
      "scriptId":"u109"},
    "fccddb75a75144dd8964e73e72ef0161":{
      "scriptId":"u110"},
    "7ee5e07712934bc091750873af90b62c":{
      "scriptId":"u111"},
    "1e1b4da90b6e447e93d074e980577bcc":{
      "scriptId":"u112"},
    "85441002e4cc4a31a99f96388dec3b74":{
      "scriptId":"u113"},
    "a032a0b6899d4c66869b4b926f367218":{
      "scriptId":"u114"},
    "a5183dd646f44162a5cd5be45f5a227b":{
      "scriptId":"u115"},
    "c6f5d2b636a8456eaf97a495b3deb0e4":{
      "scriptId":"u116"},
    "d54107db091b4fa19d9e779caea106c0":{
      "scriptId":"u117"},
    "6930ef56dc3d4f44b960e28c4bf99ed9":{
      "scriptId":"u118"},
    "4471199f5e324058bad0cf95a0767fe2":{
      "scriptId":"u119"},
    "c8587cb9442f4494bd0757b7327c7a0a":{
      "scriptId":"u120"},
    "a8b72f697a514b14a2239c6a9e11056d":{
      "scriptId":"u121"}}});