$axure.loadCurrentPage({
  "url":"付费拦截页面（聊天拦截）.html",
  "generationDate":new Date(1429020442515.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7c132e0074eb484b9646e8168657cd7e",
    "type":"Axure:Page",
    "name":"付费拦截页面（聊天拦截）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e1b7aa49d6654c4ca44676e1c1fa040f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":320,
              "height":580}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a85d15f30ffa4d8e9fa2bbfb6aafcdcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":320,
                  "height":580}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u0.png"}},
{
          "id":"5a50c64d6ddf4fd0a72bb3350f51e4f2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":56},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"16983b3a2bf546feb6bd3819e9f53333",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":56,
              "y":34},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e73bdda8242a4a68baa1eaeabacdc2af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":56,
                  "y":34},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a00db6a93814581b6398f2b50ae07d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":139,
              "y":32},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfcbf8a2dc944585b5aa687009cfb924",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":139,
                  "y":32},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97b7fdd068c74235b16bef87951fe424",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":66},
            "size":{
              "width":300,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deacb2e1e1894bd0bed5aa044d563278",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":66},
                "size":{
                  "width":300,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u7.png"}},
{
          "id":"a1e7cbbf83f6406294ca3e60b9d760b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":56,
              "y":75},
            "size":{
              "width":60,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3797fc8ebbd64393bea4a6eee8d0c87f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":56,
                  "y":75},
                "size":{
                  "width":60,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u9.png"}},
{
          "id":"1376be61893b48299c660b47eb339be1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":126,
              "y":76},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e9288ef75074b65a005706682543c51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":126,
                  "y":76},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3680eeb1021246158f45cc65685868f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":126,
              "y":105},
            "size":{
              "width":225,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53bacb2297144fd4a48ea92de2ad09f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":126,
                  "y":105},
                "size":{
                  "width":225,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16165be7a725435d9f7267090a6078ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":144},
            "size":{
              "width":280,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b25e4374f4514bd184195dc6967ea6a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":144},
                "size":{
                  "width":280,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u15.png"}},
{
          "id":"ec4f5cbf0cfe45dca00019b19df2bdce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":190},
            "size":{
              "width":280,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6c59c5a0ff44d8da769b81bd816d1c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":190},
                "size":{
                  "width":280,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u15.png"}},
{
          "id":"176bd0c8e79e4d2d8b163b3068d90194",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":235},
            "size":{
              "width":280,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b08f0520b7043529b1c4379bebcf69a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":235},
                "size":{
                  "width":280,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u15.png"}},
{
          "id":"f49c8f6d0d344f0480a7dfa4c26b99d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":154},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5a2b240c6524ec38bb702a8a5ef7cff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":154},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3358023701e14530843e31a647538269",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":200},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f947601dcf6f4a1494db43b2a14bd3d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":200},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00e435713d8f48ee867c3a0bf52bee0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":244},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b3000576fad4f3d90ac0ce31976fd70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":244},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27056861f49646a58baca1bc764a9d4f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":147},
            "size":{
              "width":10,
              "height":30}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/付费拦截页面（聊天拦截）/u27_line.png"}},
{
          "id":"328584edd91e460abdac89054b1a1676",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":154},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f28ece39489a4a4496ed5132f9fa24f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":154},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91a97cbe07d44e9dae767446de9c8a10",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":193},
            "size":{
              "width":10,
              "height":30}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/付费拦截页面（聊天拦截）/u27_line.png"}},
{
          "id":"31abfc9d20af41b79e55513f24c3118e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":200},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70e3f61e620a405885966e21ae7efd5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":200},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2678b458c39d40ad982c60ce716f2b20",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":237},
            "size":{
              "width":10,
              "height":30}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/付费拦截页面（聊天拦截）/u27_line.png"}},
{
          "id":"cadc1159a73f4ac29af54bd136eab361",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":244},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92594532024d4f11a162a0cd91ed5c8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":244},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42708350736148c481325acb41c0ec4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":146},
            "size":{
              "width":80,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59b7102ec0434127b0a4ad3060edce00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":146},
                "size":{
                  "width":80,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u36.png"}},
{
          "id":"b05c013c51c74245b83bc4e6ef73e85e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":193},
            "size":{
              "width":80,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a08009936074cd6838e12ba207d8b0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":193},
                "size":{
                  "width":80,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u36.png"}},
{
          "id":"af12fa733b5b45fca78da387f4b8931f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":238},
            "size":{
              "width":80,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53cc9c40360041748ddecfff2e46140d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":238},
                "size":{
                  "width":80,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u36.png"}},
{
          "id":"6e905b07072d41d681b986ed7dd29f28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":183,
              "y":161},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"669811d9ba2f4a96a18803385f642cfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":183,
                  "y":161},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"724b1a20e49944f29cbbfc4f3fb17ae9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":182,
              "y":207},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3683c6c879c41b0adbcbcfdfc5b287a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":182,
                  "y":207},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e616f4aac4941c6bbf3559afa8a505f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":300},
            "size":{
              "width":300,
              "height":280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a03c15cfa5ef4dc390847b22f581bdaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":300},
                "size":{
                  "width":300,
                  "height":280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u46.png"}},
{
          "id":"4ba444764c0b4dcc8c68325c3a834f2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55.5,
              "y":309},
            "size":{
              "width":60,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d6b6ffd3e39454b9621e13a579dec4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55.5,
                  "y":309},
                "size":{
                  "width":60,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u9.png"}},
{
          "id":"02d69be9ce1747008c4a9896507a9ffb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":126,
              "y":310},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55388ff24a124d84a371fe4dbdabaffd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":126,
                  "y":310},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8f3aedbd4714ee19736abe166989c9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":126,
              "y":339},
            "size":{
              "width":204,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70cb56ee7ea344d39736588304a406e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":126,
                  "y":339},
                "size":{
                  "width":204,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8ddc92ed3104158b4f79b7c59d5a75e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":440},
            "size":{
              "width":280,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2020a6525be348ea8922b92ce7ab4af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":440},
                "size":{
                  "width":280,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u15.png"}},
{
          "id":"262d7be5ed184e9ba35087c6f6ce965d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":486},
            "size":{
              "width":280,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70491e8e8a4c445d978bc045ce353178",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":486},
                "size":{
                  "width":280,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u15.png"}},
{
          "id":"e92a836cfcce4328a0ef53127d8df332",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":531},
            "size":{
              "width":280,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3bf1aed64a14d8e88401a7728fbb69c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":531},
                "size":{
                  "width":280,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u15.png"}},
{
          "id":"d43b7765803843af9fdaa8cc5cc01442",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":450},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d194c28a5cf14a8bab91ef878c7e6cad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":450},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10ee23ff27ed429a9179fd8203057cdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":76,
              "y":496},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f6e7334059a48e284e187a43b1fff0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":76,
                  "y":496},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cffa341a3f1e4d9cb2728610a30bf0ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":76,
              "y":540},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feed2ddb4468452d938bbc938e76f2b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":76,
                  "y":540},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffa8f5720d3949af91bc8a215d9e1cbd",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":443},
            "size":{
              "width":10,
              "height":30}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/付费拦截页面（聊天拦截）/u27_line.png"}},
{
          "id":"827e3b84db764f11a2ac49fc3d95e9b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":450},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee2e2fc8962b4c7fbf80c941573a99dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":450},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15442c25bed14d08b9217f018ee18af7",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":489},
            "size":{
              "width":10,
              "height":30}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/付费拦截页面（聊天拦截）/u27_line.png"}},
{
          "id":"fc0fe89fd5584b999e6918623d2507a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":496},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"471746025856483ca61a8b983cdef24d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":496},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb28209221894ff6940a1472e420869f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":533},
            "size":{
              "width":10,
              "height":30}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/付费拦截页面（聊天拦截）/u27_line.png"}},
{
          "id":"78ea99f111894e8692eee86116dce2d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":540},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12bc3ddffb884f5898ccb1955b9eed6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":540},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3634ab95db9e4f50bdb099c46b3d843d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":442},
            "size":{
              "width":80,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0d6516ceea24e31ac882d90ee50f85c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":442},
                "size":{
                  "width":80,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u36.png"}},
{
          "id":"d4786351d7014e2787e3e0ed7b22b172",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":489},
            "size":{
              "width":80,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10fd1305713d421ca467b1a3fd112ffd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":489},
                "size":{
                  "width":80,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u36.png"}},
{
          "id":"134decde9e7944ca81be4bb383334b9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":534},
            "size":{
              "width":80,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bcb992f542c455bba44d1a59bf05b08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":534},
                "size":{
                  "width":80,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费拦截页面（聊天拦截）/u36.png"}},
{
          "id":"fe67a0753aff4b469bc4924b89b3c6bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":182,
              "y":457},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2d06b52e55d40b1978bc8b65c427225",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":182,
                  "y":457},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"157c0e2bf6754e7cb284daba0e274113",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":182,
              "y":503},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25b05b288532454e94af0e1a7831c571",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":182,
                  "y":503},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"040f10a1566c4f5caf8544dd3c57484b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":368},
            "size":{
              "width":300,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d78e899d53a47bc908201d21e58e77b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":368},
                "size":{
                  "width":300,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e1b7aa49d6654c4ca44676e1c1fa040f":{
      "scriptId":"u0"},
    "a85d15f30ffa4d8e9fa2bbfb6aafcdcb":{
      "scriptId":"u1"},
    "5a50c64d6ddf4fd0a72bb3350f51e4f2":{
      "scriptId":"u2"},
    "16983b3a2bf546feb6bd3819e9f53333":{
      "scriptId":"u3"},
    "e73bdda8242a4a68baa1eaeabacdc2af":{
      "scriptId":"u4"},
    "3a00db6a93814581b6398f2b50ae07d8":{
      "scriptId":"u5"},
    "cfcbf8a2dc944585b5aa687009cfb924":{
      "scriptId":"u6"},
    "97b7fdd068c74235b16bef87951fe424":{
      "scriptId":"u7"},
    "deacb2e1e1894bd0bed5aa044d563278":{
      "scriptId":"u8"},
    "a1e7cbbf83f6406294ca3e60b9d760b6":{
      "scriptId":"u9"},
    "3797fc8ebbd64393bea4a6eee8d0c87f":{
      "scriptId":"u10"},
    "1376be61893b48299c660b47eb339be1":{
      "scriptId":"u11"},
    "5e9288ef75074b65a005706682543c51":{
      "scriptId":"u12"},
    "3680eeb1021246158f45cc65685868f9":{
      "scriptId":"u13"},
    "53bacb2297144fd4a48ea92de2ad09f0":{
      "scriptId":"u14"},
    "16165be7a725435d9f7267090a6078ad":{
      "scriptId":"u15"},
    "b25e4374f4514bd184195dc6967ea6a5":{
      "scriptId":"u16"},
    "ec4f5cbf0cfe45dca00019b19df2bdce":{
      "scriptId":"u17"},
    "d6c59c5a0ff44d8da769b81bd816d1c9":{
      "scriptId":"u18"},
    "176bd0c8e79e4d2d8b163b3068d90194":{
      "scriptId":"u19"},
    "6b08f0520b7043529b1c4379bebcf69a":{
      "scriptId":"u20"},
    "f49c8f6d0d344f0480a7dfa4c26b99d7":{
      "scriptId":"u21"},
    "c5a2b240c6524ec38bb702a8a5ef7cff":{
      "scriptId":"u22"},
    "3358023701e14530843e31a647538269":{
      "scriptId":"u23"},
    "f947601dcf6f4a1494db43b2a14bd3d8":{
      "scriptId":"u24"},
    "00e435713d8f48ee867c3a0bf52bee0b":{
      "scriptId":"u25"},
    "3b3000576fad4f3d90ac0ce31976fd70":{
      "scriptId":"u26"},
    "27056861f49646a58baca1bc764a9d4f":{
      "scriptId":"u27"},
    "328584edd91e460abdac89054b1a1676":{
      "scriptId":"u28"},
    "f28ece39489a4a4496ed5132f9fa24f8":{
      "scriptId":"u29"},
    "91a97cbe07d44e9dae767446de9c8a10":{
      "scriptId":"u30"},
    "31abfc9d20af41b79e55513f24c3118e":{
      "scriptId":"u31"},
    "70e3f61e620a405885966e21ae7efd5c":{
      "scriptId":"u32"},
    "2678b458c39d40ad982c60ce716f2b20":{
      "scriptId":"u33"},
    "cadc1159a73f4ac29af54bd136eab361":{
      "scriptId":"u34"},
    "92594532024d4f11a162a0cd91ed5c8e":{
      "scriptId":"u35"},
    "42708350736148c481325acb41c0ec4f":{
      "scriptId":"u36"},
    "59b7102ec0434127b0a4ad3060edce00":{
      "scriptId":"u37"},
    "b05c013c51c74245b83bc4e6ef73e85e":{
      "scriptId":"u38"},
    "4a08009936074cd6838e12ba207d8b0a":{
      "scriptId":"u39"},
    "af12fa733b5b45fca78da387f4b8931f":{
      "scriptId":"u40"},
    "53cc9c40360041748ddecfff2e46140d":{
      "scriptId":"u41"},
    "6e905b07072d41d681b986ed7dd29f28":{
      "scriptId":"u42"},
    "669811d9ba2f4a96a18803385f642cfa":{
      "scriptId":"u43"},
    "724b1a20e49944f29cbbfc4f3fb17ae9":{
      "scriptId":"u44"},
    "a3683c6c879c41b0adbcbcfdfc5b287a":{
      "scriptId":"u45"},
    "9e616f4aac4941c6bbf3559afa8a505f":{
      "scriptId":"u46"},
    "a03c15cfa5ef4dc390847b22f581bdaa":{
      "scriptId":"u47"},
    "4ba444764c0b4dcc8c68325c3a834f2f":{
      "scriptId":"u48"},
    "2d6b6ffd3e39454b9621e13a579dec4d":{
      "scriptId":"u49"},
    "02d69be9ce1747008c4a9896507a9ffb":{
      "scriptId":"u50"},
    "55388ff24a124d84a371fe4dbdabaffd":{
      "scriptId":"u51"},
    "c8f3aedbd4714ee19736abe166989c9b":{
      "scriptId":"u52"},
    "70cb56ee7ea344d39736588304a406e5":{
      "scriptId":"u53"},
    "d8ddc92ed3104158b4f79b7c59d5a75e":{
      "scriptId":"u54"},
    "2020a6525be348ea8922b92ce7ab4af4":{
      "scriptId":"u55"},
    "262d7be5ed184e9ba35087c6f6ce965d":{
      "scriptId":"u56"},
    "70491e8e8a4c445d978bc045ce353178":{
      "scriptId":"u57"},
    "e92a836cfcce4328a0ef53127d8df332":{
      "scriptId":"u58"},
    "d3bf1aed64a14d8e88401a7728fbb69c":{
      "scriptId":"u59"},
    "d43b7765803843af9fdaa8cc5cc01442":{
      "scriptId":"u60"},
    "d194c28a5cf14a8bab91ef878c7e6cad":{
      "scriptId":"u61"},
    "10ee23ff27ed429a9179fd8203057cdd":{
      "scriptId":"u62"},
    "1f6e7334059a48e284e187a43b1fff0e":{
      "scriptId":"u63"},
    "cffa341a3f1e4d9cb2728610a30bf0ad":{
      "scriptId":"u64"},
    "feed2ddb4468452d938bbc938e76f2b8":{
      "scriptId":"u65"},
    "ffa8f5720d3949af91bc8a215d9e1cbd":{
      "scriptId":"u66"},
    "827e3b84db764f11a2ac49fc3d95e9b5":{
      "scriptId":"u67"},
    "ee2e2fc8962b4c7fbf80c941573a99dc":{
      "scriptId":"u68"},
    "15442c25bed14d08b9217f018ee18af7":{
      "scriptId":"u69"},
    "fc0fe89fd5584b999e6918623d2507a8":{
      "scriptId":"u70"},
    "471746025856483ca61a8b983cdef24d":{
      "scriptId":"u71"},
    "eb28209221894ff6940a1472e420869f":{
      "scriptId":"u72"},
    "78ea99f111894e8692eee86116dce2d5":{
      "scriptId":"u73"},
    "12bc3ddffb884f5898ccb1955b9eed6b":{
      "scriptId":"u74"},
    "3634ab95db9e4f50bdb099c46b3d843d":{
      "scriptId":"u75"},
    "e0d6516ceea24e31ac882d90ee50f85c":{
      "scriptId":"u76"},
    "d4786351d7014e2787e3e0ed7b22b172":{
      "scriptId":"u77"},
    "10fd1305713d421ca467b1a3fd112ffd":{
      "scriptId":"u78"},
    "134decde9e7944ca81be4bb383334b9c":{
      "scriptId":"u79"},
    "8bcb992f542c455bba44d1a59bf05b08":{
      "scriptId":"u80"},
    "fe67a0753aff4b469bc4924b89b3c6bd":{
      "scriptId":"u81"},
    "b2d06b52e55d40b1978bc8b65c427225":{
      "scriptId":"u82"},
    "157c0e2bf6754e7cb284daba0e274113":{
      "scriptId":"u83"},
    "25b05b288532454e94af0e1a7831c571":{
      "scriptId":"u84"},
    "040f10a1566c4f5caf8544dd3c57484b":{
      "scriptId":"u85"},
    "7d78e899d53a47bc908201d21e58e77b":{
      "scriptId":"u86"}}});