$axure.loadCurrentPage({
  "url":"关注.html",
  "generationDate":new Date(1429020442747.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b91315e81e95458b87a966bbc9b61c29",
    "type":"Axure:Page",
    "name":"关注",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a6a243a36384463abb198d1903f6fd42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cb6eed1085f4cb6950ffe14c5172905",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u0.png"}},
{
          "id":"1fd7f0f0c7dd4cad9fa8dd555be3334f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":64},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"f45de27ed335403ca8f2b99bfe78d696",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":465},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f71fc18b430a405b85b7025c782f07a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":465},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"a8de6f762e8c42b1a95c2a8787618d9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df94173a062146448261fc1a6608b40f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"718687692c724244be1286b3e093aaf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90241b165c844c59839a6be2de5c7eaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"c6d0ead3b85646dc8d1e481b636d4c73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9b50015cb254dd5b8475dbfeba7400d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"6e9dcb58315f46a387315fe53c2235bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":179.5,
              "y":32},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"686b2a55aac048f48b7ab8dddb92fc74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":179.5,
                  "y":32},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f196b4ece444322aa7799eec4b62647",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":456},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"87eeacd16d2a469cb5cc5218518b0c47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20b2a1ead7d7461fba9a16afcbb4228b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"98e3588990cb42d8ac9da4b57f3912df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":74},
            "size":{
              "width":300,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"165b1b55ed0b4fa6a77d5961700071f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":74},
                "size":{
                  "width":300,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u16.png"}},
{
          "id":"d8c237611cea42a396685fe0a52f7491",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":74},
            "size":{
              "width":10,
              "height":26}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/关注/u18_line.png"}},
{
          "id":"ddbd22b042f64a349c1d0392a5b2e9dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":79},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3000144c282e45d09d43afeae6555f60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":97,
                  "y":79},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a201ef9e154407eac167cd7d6ec2c00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":79},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53218517ab6741bf8ec44fabe816a4f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":237,
                  "y":79},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"178df4c40a5948c4affadabb030f7314",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":456},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd44193e72f24b4c88341dac81223b49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":201,
                  "y":456},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u23.png"}},
{
          "id":"696a8df1c9234e09996fa3ffc888561d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":85,
              "y":160},
            "size":{
              "width":230,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02c8f49957974f7da1630eecf1c7f834",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":85,
                  "y":160},
                "size":{
                  "width":230,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u25.png"}},
{
          "id":"1d0857d49c874deda7c43eda1f8b0b4e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":295},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a65d163de586449e90a6db9bbd45e3e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":520},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d02ded50456349b6b4c9c22be441fb1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":520},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u0.png"}},
{
          "id":"786653d44daa4c0b92e9532b02d965c7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":564},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"25546dd4140e4f26bf9664d23c6bd48b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":965},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e18aae75b8142d79239f9ff817e174e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":965},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"ba857b7195974b7f84d41dd0c554ee3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":966},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"548d92bdb8964f9d8fbdb7dc936af12f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":966},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"2ab8ff2ee3924ef6a700e6025aad6d14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":966},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c37969e020df4e9cbe03a85a96f0500b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":966},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"b198f5ecaeaa45578c2f4b2036dae96b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":966},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a3b31b0e88a455fa14799997d8d359d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":966},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"0b63b185a04040b1a4b5daf9cf0b952c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":180,
              "y":532},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d7b1e8a73d74fdcb4c7f9528990b5d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":180,
                  "y":532},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"100cc2974fa6434a82336f44ae70df41",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":956},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"cc697be877614ea19ad630d894e4fc8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":966},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96a34aeba115465788fd5c8b6501dfe6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":966},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"b3a73e1784d94b829e1860a3bc141de5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":574},
            "size":{
              "width":300,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5693a42046ca4f6eb1cb6c0984f20ed0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":574},
                "size":{
                  "width":300,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u16.png"}},
{
          "id":"7c20955d0377420bab57e2825305fe59",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":574},
            "size":{
              "width":10,
              "height":26}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/关注/u18_line.png"}},
{
          "id":"d5d19a5b5cfb45e0910960db9288a260",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":579},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"039d222bbddb490e855767b44a1fa727",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":579},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84717b3da8134a3b8e87fb32fcf2e995",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":579},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aaeebbe897f4fad84a96890bcac6b04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":237,
                  "y":579},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c4d2f0269e94d8a91cda27d81650d2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":956},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f2674b307ab466494646360787ed62c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":201,
                  "y":956},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u23.png"}},
{
          "id":"399eb27339e54c8792494dd6c548c6d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":85,
              "y":660},
            "size":{
              "width":230,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58b2751573f842a58b1d3b637166085a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":85,
                  "y":660},
                "size":{
                  "width":230,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u25.png"}},
{
          "id":"cdefecf146cf4b1799fd1cd8aa954509",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":795},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9a4618c8cc954f04ab4c8dddcf81393b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":330},
            "size":{
              "width":217,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e60ceffffaae4b5e9297298e96768c2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":330},
                "size":{
                  "width":217,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b02e605e4ee47e6b291ec6bb5a90bd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":830},
            "size":{
              "width":217,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"077d81e0f2b747708a7efe0449911702",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":830},
                "size":{
                  "width":217,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc9cec6c67774dc9966149b4c55a3a16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":20},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd54e7fe8ce140f1b30d66f3bd0054ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":20},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u0.png"}},
{
          "id":"b60cab8a0dbc436dabf0c19cb554643f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":64},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"af875332a498465688136f1ed58643f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":465},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25c6be0aec764e09b7a2bf9acb5b8c59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":465},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"c2d687c8174e4caa8764e9a88cdb931e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":545,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"713dc12ac1df4bd0bc0729324175b453",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":545,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"e635ec2a297e4dd694e72a8b9d5cac6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0024b90be5364811b791b1eb808b7b21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"cbb053e0c81a400faad18de4e7169698",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":669,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a12dc5dac114e0783d8d40b5733c79d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":669,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"b0aa1dcd06ea4f7d8e224b90f3ff4970",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":540,
              "y":32},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5d39bf87d5a4dc78343e6cad26d2bb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":540,
                  "y":32},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfdd18dbc5524e7ca8295d3e497c74b2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":456},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"44734334aa7f4e4aa18743d1216f6117",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1365659ed7474de7ab708767dc166863",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"2a35c3a32a1c46dc8d4867b3e897b6f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":74},
            "size":{
              "width":300,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77041bc2bbb54d43a11e791afc71d199",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":74},
                "size":{
                  "width":300,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u16.png"}},
{
          "id":"4d24df4547244fc5acb49220a155cb3e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":555,
              "y":74},
            "size":{
              "width":10,
              "height":26}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/关注/u18_line.png"}},
{
          "id":"d7f50a7d70eb4742b591038e4fe020a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":458,
              "y":79},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"528b477381bc4fc88577fae77c11cd85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":458,
                  "y":79},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43ffd597006648608909ec06bfa3bcbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":608,
              "y":79},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fa8c8aa179f49ad99821dbaec07c9c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":608,
                  "y":79},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"856c8e952032473e9048bdb423ce5499",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":561,
              "y":456},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce2ee366c8ae4d8c995125779212e4ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":561,
                  "y":456},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u23.png"}},
{
          "id":"2ce75de2c6534b96b58fa51689bb0a82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":445,
              "y":160},
            "size":{
              "width":230,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"291f32780c9e43428a17f2d9ac86518f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":445,
                  "y":160},
                "size":{
                  "width":230,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u25.png"}},
{
          "id":"172812859b044db1bbf85a4495f52b19",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":295},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5e210bb28466454b8fd5014b65f13853",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":452,
              "y":330},
            "size":{
              "width":217,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4d1bad4251b48ce823d64a774c8c33c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":452,
                  "y":330},
                "size":{
                  "width":217,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1081823415da4a2a9eb9aa90e1dd3dd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":520},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfd8c617e3d6473eb553e57df6444bd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":520},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u0.png"}},
{
          "id":"67546a373c8c40c9b006478077c2821c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":564},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"36c46cf3dafe46c79d6a0f7aab6ca2ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":965},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bf2b24c3bba4fe68a7cdeb53a807c6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":965},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"3e244154a0494bb9ab3f31231925f9f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":545,
              "y":966},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"693a2d2028e845dfadf082e1cc20cb69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":545,
                  "y":966},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"d2fdd8398cca432181b315d25ff59277",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":966},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bafc437702284c36bc8e84c09e2ff668",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":966},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"3724eec3b7554885b93928d44cee96fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":669,
              "y":966},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71620ef6c0ee4c29bf5a6b59b8af536a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":669,
                  "y":966},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"2c597628d8164b0a882d91e09215b2d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":540,
              "y":532},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d90dc0b60e1f44f3a0df11b9eb9305dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":540,
                  "y":532},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1c6f68346b048159f75a3714d8c894b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":956},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"8292d8d66db44a7b84e208a3b0681dc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":966},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef3c411dcf9b45b4b9e8d16b9ac1f71a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":966},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"d54a1a6fd45143abae011439a7fef65e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":574},
            "size":{
              "width":300,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4bc6666844e481b96f539d7b7952814",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":574},
                "size":{
                  "width":300,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u16.png"}},
{
          "id":"a740a5eae8f74f04a0811057ce02273a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":555,
              "y":574},
            "size":{
              "width":10,
              "height":26}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/关注/u18_line.png"}},
{
          "id":"d62f8932b67040c99e02c351eba80561",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":459,
              "y":579},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"696258b5eb3f4e449e19101344c00319",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":459,
                  "y":579},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06fe3dc86fb14b7da3f1a0d3f84909d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":607,
              "y":579},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cde3c5887fbe4a2e9ed2016310ab104f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":607,
                  "y":579},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be9f411bf75b4db3b27805ad7eb3ec1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":561,
              "y":956},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"558bcce3e7a04e319c729c4d8e8f905a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":561,
                  "y":956},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u23.png"}},
{
          "id":"f4cd9ce0100143a4a0d473f9986ac22a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":445,
              "y":660},
            "size":{
              "width":230,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53a7ff6b049a4bd1b6efe2f7a33a098d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":445,
                  "y":660},
                "size":{
                  "width":230,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u25.png"}},
{
          "id":"c28caa5eec3b46f4bdb5b0451a335c57",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":795},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3dac399f328546d492d85a148ab05fd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":452,
              "y":830},
            "size":{
              "width":217,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14c5dd8abbeb44e0b11bb459535cc5fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":452,
                  "y":830},
                "size":{
                  "width":217,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76205f4eea024016a20dba3b998040be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":156,
              "y":82},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8136f03f4334402b436e7a5d6cfffb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":156,
                  "y":82},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u120.png"}},
{
          "id":"e81f138e68b34ece86037810d0469607",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":144,
              "y":465},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"793c8d7f946a4c9c88dc7e55e81a8503",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":144,
                  "y":465},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u120.png"}},
{
          "id":"39faaaf3842545f3b52e76ab785696f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":147,
              "y":965},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7b65b94a1184570b7f645ff7dcaeb6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":147,
                  "y":965},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u120.png"}},
{
          "id":"9d710c830ddd403ab2461cb31bb888c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":150,
              "y":582},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ab44c1d192a4e44a7fb712a9445fbaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":150,
                  "y":582},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注/u120.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a6a243a36384463abb198d1903f6fd42":{
      "scriptId":"u0"},
    "5cb6eed1085f4cb6950ffe14c5172905":{
      "scriptId":"u1"},
    "1fd7f0f0c7dd4cad9fa8dd555be3334f":{
      "scriptId":"u2"},
    "f45de27ed335403ca8f2b99bfe78d696":{
      "scriptId":"u3"},
    "f71fc18b430a405b85b7025c782f07a0":{
      "scriptId":"u4"},
    "a8de6f762e8c42b1a95c2a8787618d9c":{
      "scriptId":"u5"},
    "df94173a062146448261fc1a6608b40f":{
      "scriptId":"u6"},
    "718687692c724244be1286b3e093aaf7":{
      "scriptId":"u7"},
    "90241b165c844c59839a6be2de5c7eaf":{
      "scriptId":"u8"},
    "c6d0ead3b85646dc8d1e481b636d4c73":{
      "scriptId":"u9"},
    "d9b50015cb254dd5b8475dbfeba7400d":{
      "scriptId":"u10"},
    "6e9dcb58315f46a387315fe53c2235bf":{
      "scriptId":"u11"},
    "686b2a55aac048f48b7ab8dddb92fc74":{
      "scriptId":"u12"},
    "8f196b4ece444322aa7799eec4b62647":{
      "scriptId":"u13"},
    "87eeacd16d2a469cb5cc5218518b0c47":{
      "scriptId":"u14"},
    "20b2a1ead7d7461fba9a16afcbb4228b":{
      "scriptId":"u15"},
    "98e3588990cb42d8ac9da4b57f3912df":{
      "scriptId":"u16"},
    "165b1b55ed0b4fa6a77d5961700071f1":{
      "scriptId":"u17"},
    "d8c237611cea42a396685fe0a52f7491":{
      "scriptId":"u18"},
    "ddbd22b042f64a349c1d0392a5b2e9dd":{
      "scriptId":"u19"},
    "3000144c282e45d09d43afeae6555f60":{
      "scriptId":"u20"},
    "0a201ef9e154407eac167cd7d6ec2c00":{
      "scriptId":"u21"},
    "53218517ab6741bf8ec44fabe816a4f6":{
      "scriptId":"u22"},
    "178df4c40a5948c4affadabb030f7314":{
      "scriptId":"u23"},
    "fd44193e72f24b4c88341dac81223b49":{
      "scriptId":"u24"},
    "696a8df1c9234e09996fa3ffc888561d":{
      "scriptId":"u25"},
    "02c8f49957974f7da1630eecf1c7f834":{
      "scriptId":"u26"},
    "1d0857d49c874deda7c43eda1f8b0b4e":{
      "scriptId":"u27"},
    "a65d163de586449e90a6db9bbd45e3e5":{
      "scriptId":"u28"},
    "d02ded50456349b6b4c9c22be441fb1a":{
      "scriptId":"u29"},
    "786653d44daa4c0b92e9532b02d965c7":{
      "scriptId":"u30"},
    "25546dd4140e4f26bf9664d23c6bd48b":{
      "scriptId":"u31"},
    "6e18aae75b8142d79239f9ff817e174e":{
      "scriptId":"u32"},
    "ba857b7195974b7f84d41dd0c554ee3e":{
      "scriptId":"u33"},
    "548d92bdb8964f9d8fbdb7dc936af12f":{
      "scriptId":"u34"},
    "2ab8ff2ee3924ef6a700e6025aad6d14":{
      "scriptId":"u35"},
    "c37969e020df4e9cbe03a85a96f0500b":{
      "scriptId":"u36"},
    "b198f5ecaeaa45578c2f4b2036dae96b":{
      "scriptId":"u37"},
    "2a3b31b0e88a455fa14799997d8d359d":{
      "scriptId":"u38"},
    "0b63b185a04040b1a4b5daf9cf0b952c":{
      "scriptId":"u39"},
    "3d7b1e8a73d74fdcb4c7f9528990b5d8":{
      "scriptId":"u40"},
    "100cc2974fa6434a82336f44ae70df41":{
      "scriptId":"u41"},
    "cc697be877614ea19ad630d894e4fc8f":{
      "scriptId":"u42"},
    "96a34aeba115465788fd5c8b6501dfe6":{
      "scriptId":"u43"},
    "b3a73e1784d94b829e1860a3bc141de5":{
      "scriptId":"u44"},
    "5693a42046ca4f6eb1cb6c0984f20ed0":{
      "scriptId":"u45"},
    "7c20955d0377420bab57e2825305fe59":{
      "scriptId":"u46"},
    "d5d19a5b5cfb45e0910960db9288a260":{
      "scriptId":"u47"},
    "039d222bbddb490e855767b44a1fa727":{
      "scriptId":"u48"},
    "84717b3da8134a3b8e87fb32fcf2e995":{
      "scriptId":"u49"},
    "0aaeebbe897f4fad84a96890bcac6b04":{
      "scriptId":"u50"},
    "3c4d2f0269e94d8a91cda27d81650d2a":{
      "scriptId":"u51"},
    "4f2674b307ab466494646360787ed62c":{
      "scriptId":"u52"},
    "399eb27339e54c8792494dd6c548c6d1":{
      "scriptId":"u53"},
    "58b2751573f842a58b1d3b637166085a":{
      "scriptId":"u54"},
    "cdefecf146cf4b1799fd1cd8aa954509":{
      "scriptId":"u55"},
    "9a4618c8cc954f04ab4c8dddcf81393b":{
      "scriptId":"u56"},
    "e60ceffffaae4b5e9297298e96768c2e":{
      "scriptId":"u57"},
    "3b02e605e4ee47e6b291ec6bb5a90bd6":{
      "scriptId":"u58"},
    "077d81e0f2b747708a7efe0449911702":{
      "scriptId":"u59"},
    "fc9cec6c67774dc9966149b4c55a3a16":{
      "scriptId":"u60"},
    "cd54e7fe8ce140f1b30d66f3bd0054ce":{
      "scriptId":"u61"},
    "b60cab8a0dbc436dabf0c19cb554643f":{
      "scriptId":"u62"},
    "af875332a498465688136f1ed58643f6":{
      "scriptId":"u63"},
    "25c6be0aec764e09b7a2bf9acb5b8c59":{
      "scriptId":"u64"},
    "c2d687c8174e4caa8764e9a88cdb931e":{
      "scriptId":"u65"},
    "713dc12ac1df4bd0bc0729324175b453":{
      "scriptId":"u66"},
    "e635ec2a297e4dd694e72a8b9d5cac6d":{
      "scriptId":"u67"},
    "0024b90be5364811b791b1eb808b7b21":{
      "scriptId":"u68"},
    "cbb053e0c81a400faad18de4e7169698":{
      "scriptId":"u69"},
    "0a12dc5dac114e0783d8d40b5733c79d":{
      "scriptId":"u70"},
    "b0aa1dcd06ea4f7d8e224b90f3ff4970":{
      "scriptId":"u71"},
    "d5d39bf87d5a4dc78343e6cad26d2bb8":{
      "scriptId":"u72"},
    "cfdd18dbc5524e7ca8295d3e497c74b2":{
      "scriptId":"u73"},
    "44734334aa7f4e4aa18743d1216f6117":{
      "scriptId":"u74"},
    "1365659ed7474de7ab708767dc166863":{
      "scriptId":"u75"},
    "2a35c3a32a1c46dc8d4867b3e897b6f8":{
      "scriptId":"u76"},
    "77041bc2bbb54d43a11e791afc71d199":{
      "scriptId":"u77"},
    "4d24df4547244fc5acb49220a155cb3e":{
      "scriptId":"u78"},
    "d7f50a7d70eb4742b591038e4fe020a9":{
      "scriptId":"u79"},
    "528b477381bc4fc88577fae77c11cd85":{
      "scriptId":"u80"},
    "43ffd597006648608909ec06bfa3bcbd":{
      "scriptId":"u81"},
    "4fa8c8aa179f49ad99821dbaec07c9c7":{
      "scriptId":"u82"},
    "856c8e952032473e9048bdb423ce5499":{
      "scriptId":"u83"},
    "ce2ee366c8ae4d8c995125779212e4ca":{
      "scriptId":"u84"},
    "2ce75de2c6534b96b58fa51689bb0a82":{
      "scriptId":"u85"},
    "291f32780c9e43428a17f2d9ac86518f":{
      "scriptId":"u86"},
    "172812859b044db1bbf85a4495f52b19":{
      "scriptId":"u87"},
    "5e210bb28466454b8fd5014b65f13853":{
      "scriptId":"u88"},
    "e4d1bad4251b48ce823d64a774c8c33c":{
      "scriptId":"u89"},
    "1081823415da4a2a9eb9aa90e1dd3dd3":{
      "scriptId":"u90"},
    "cfd8c617e3d6473eb553e57df6444bd2":{
      "scriptId":"u91"},
    "67546a373c8c40c9b006478077c2821c":{
      "scriptId":"u92"},
    "36c46cf3dafe46c79d6a0f7aab6ca2ac":{
      "scriptId":"u93"},
    "5bf2b24c3bba4fe68a7cdeb53a807c6e":{
      "scriptId":"u94"},
    "3e244154a0494bb9ab3f31231925f9f8":{
      "scriptId":"u95"},
    "693a2d2028e845dfadf082e1cc20cb69":{
      "scriptId":"u96"},
    "d2fdd8398cca432181b315d25ff59277":{
      "scriptId":"u97"},
    "bafc437702284c36bc8e84c09e2ff668":{
      "scriptId":"u98"},
    "3724eec3b7554885b93928d44cee96fb":{
      "scriptId":"u99"},
    "71620ef6c0ee4c29bf5a6b59b8af536a":{
      "scriptId":"u100"},
    "2c597628d8164b0a882d91e09215b2d9":{
      "scriptId":"u101"},
    "d90dc0b60e1f44f3a0df11b9eb9305dc":{
      "scriptId":"u102"},
    "b1c6f68346b048159f75a3714d8c894b":{
      "scriptId":"u103"},
    "8292d8d66db44a7b84e208a3b0681dc9":{
      "scriptId":"u104"},
    "ef3c411dcf9b45b4b9e8d16b9ac1f71a":{
      "scriptId":"u105"},
    "d54a1a6fd45143abae011439a7fef65e":{
      "scriptId":"u106"},
    "f4bc6666844e481b96f539d7b7952814":{
      "scriptId":"u107"},
    "a740a5eae8f74f04a0811057ce02273a":{
      "scriptId":"u108"},
    "d62f8932b67040c99e02c351eba80561":{
      "scriptId":"u109"},
    "696258b5eb3f4e449e19101344c00319":{
      "scriptId":"u110"},
    "06fe3dc86fb14b7da3f1a0d3f84909d8":{
      "scriptId":"u111"},
    "cde3c5887fbe4a2e9ed2016310ab104f":{
      "scriptId":"u112"},
    "be9f411bf75b4db3b27805ad7eb3ec1b":{
      "scriptId":"u113"},
    "558bcce3e7a04e319c729c4d8e8f905a":{
      "scriptId":"u114"},
    "f4cd9ce0100143a4a0d473f9986ac22a":{
      "scriptId":"u115"},
    "53a7ff6b049a4bd1b6efe2f7a33a098d":{
      "scriptId":"u116"},
    "c28caa5eec3b46f4bdb5b0451a335c57":{
      "scriptId":"u117"},
    "3dac399f328546d492d85a148ab05fd5":{
      "scriptId":"u118"},
    "14c5dd8abbeb44e0b11bb459535cc5fa":{
      "scriptId":"u119"},
    "76205f4eea024016a20dba3b998040be":{
      "scriptId":"u120"},
    "c8136f03f4334402b436e7a5d6cfffb2":{
      "scriptId":"u121"},
    "e81f138e68b34ece86037810d0469607":{
      "scriptId":"u122"},
    "793c8d7f946a4c9c88dc7e55e81a8503":{
      "scriptId":"u123"},
    "39faaaf3842545f3b52e76ab785696f4":{
      "scriptId":"u124"},
    "b7b65b94a1184570b7f645ff7dcaeb6d":{
      "scriptId":"u125"},
    "9d710c830ddd403ab2461cb31bb888c8":{
      "scriptId":"u126"},
    "7ab44c1d192a4e44a7fb712a9445fbaf":{
      "scriptId":"u127"}}});