$axure.loadCurrentPage({
  "url":"对方空间（我已付费）.html",
  "generationDate":new Date(1429020442270.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3a281aee46ab487093ae2bcc16648ad2",
    "type":"Axure:Page",
    "name":"对方空间（我已付费）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f9d79bf294ef4046a294cb29d331c973",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":20},
            "size":{
              "width":320,
              "height":740}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89b6f2f0934f4fee9b8257226f80f03e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":20},
                "size":{
                  "width":320,
                  "height":740}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间（未付费）/u0.png"}},
{
          "id":"8047921c459b4b44b3674710eb1efee3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":64},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"6c92b17edb804218a47cdb279e838ec2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":190,
              "y":32},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f002c26d48ac403587e35a2a81866565",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":190,
                  "y":32},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bf39f00ab0a407f9d763c599d608f38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":38},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2a58fc9d35943ff8a7a8cb7613a57f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":68,
                  "y":38},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a414ea515a640eabef6623aba767827",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":333,
              "y":38},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b293884b370745b5b705332906aaec90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":333,
                  "y":38},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e05766f9cc554d51a6be250433f9465d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":85},
            "size":{
              "width":60,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b909ffc86a714681bb680b342df083f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":85},
                "size":{
                  "width":60,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间（未付费）/u9.png"}},
{
          "id":"e8ff40eee3294abfb3b740be67f27dfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":177},
            "size":{
              "width":60,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea3a87c53e6e4d46ac037c564fa681be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":139,
                  "y":177},
                "size":{
                  "width":60,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间（未付费）/u9.png"}},
{
          "id":"1123efea69c246a7b79d694f7a0d04cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":212,
              "y":177},
            "size":{
              "width":60,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4cecbb5e7d140cc8273e165ff8e503a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":212,
                  "y":177},
                "size":{
                  "width":60,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间（未付费）/u9.png"}},
{
          "id":"9318137324e04d1cb13f33328fe0f74d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":177},
            "size":{
              "width":60,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b52029d22cb42e28a0f10d840309543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":177},
                "size":{
                  "width":60,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间（未付费）/u9.png"}},
{
          "id":"c4d6d63aa4bc499c9432b5df432c5b77",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":155},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"8617a3dae13c499e8217fb0d2eb3f0e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":177},
            "size":{
              "width":60,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b9201bd897b43249726a46d12e10c82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":177},
                "size":{
                  "width":60,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间（未付费）/u9.png"}},
{
          "id":"fd1430bc6d83443facf0c8b361cb60df",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":704},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"f3c4913d891f47679ff27ff998a6cd78",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":709},
            "size":{
              "width":10,
              "height":50}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/对方空间（未付费）/u21_line.png"}},
{
          "id":"71ac2dcd536646e9b5f7d462e1d22128",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":99,
              "y":726},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fc650409e7142b2af83ea331bc8c5f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":99,
                  "y":726},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10c71f4637f0421a86e59a8d41309d64",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":260,
              "y":727},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"784c5409ee3848d5b7b9b5dff4d9dc97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":260,
                  "y":727},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bd46020ec26483d8ccf24cdc86225c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":265},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b93f6b3249943f193578147d7eba4e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":265},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f94316ace9464c429eeb6d265a392f12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":291},
            "size":{
              "width":282,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ff11944009348d6a54a7c35125d6044",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":291},
                "size":{
                  "width":282,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33bd99f381b44389b4a5f3af29c5a30f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":454},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"260a407b5d3a4e6b9160691fdfdc9314",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":454},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0153e3a0c72415aa9e0ce83998561a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":454},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3448e0fdcd4947409972c00a5df3ec36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":454},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff578e6ece1d4acd83ff9c902760ab0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":492},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b791d2452a4c41e897a4e4bc89497111",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":492},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f18b0792cec4477ba2395b3fde4f568",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":492},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3319d38cb5044df3acb04d5b58e80606",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":492},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71437eeb30264b87b2bd7b99343f248d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":248},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"99bd45118abf45aead1a9897d8a9c15b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":438},
            "size":{
              "width":282,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/对方空间（未付费）/u39_line.png"}},
{
          "id":"bf4443db79c047a493b1f9648801a611",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":474},
            "size":{
              "width":282,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/对方空间（未付费）/u39_line.png"}},
{
          "id":"90d3f4e839c34a1f9c7f69e6d1f025cb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":515},
            "size":{
              "width":282,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/对方空间（未付费）/u39_line.png"}},
{
          "id":"8bb194b4d0b44c9991483cd528c81de8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":133,
              "y":87},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a741038f54c54b46b797cc9d86fb52f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":133,
                  "y":87},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57a6de4ada984b4fb209b4f4c92018b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":183,
              "y":87},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"911830eb8687407dbfb41f34635a787f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":183,
                  "y":87},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"118ea46ac06c46dda387e93cc0fad071",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":234,
              "y":87},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4f1db55d9474fb3bd5de4ca6730ad30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":234,
                  "y":87},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f713752e9ca45b18dd3538a14fd1492",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":535},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e137db9abee142ea9228af3473298b1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":535},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4776acc29ee4a26becaa9385262bc70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":535},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ed96af05df94df8b54391455a9d0649",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":535},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3b00cf402664e2abb94dca02a4df49b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":558},
            "size":{
              "width":282,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/对方空间（未付费）/u39_line.png"}},
{
          "id":"8237c6513b674e99a86834b0be785455",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":535},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d033d67cbf564b5d911e8bdc10f5ec4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":535},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de6eacced980435b876fef12b9f3926f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":536},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4486aee23c3a4247abf9718cfc5939f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":536},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da3177abc3f3494a81efad014262c042",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":576},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d999e73c11464714b718515f8ee7a5e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":576},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0824df5d413b40a18f66b88196d93b26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":576},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd3cd87aa0c44d87843dc2a4949d43f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":576},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee2213e8cbef4e3ab0ba47fb92ec4ece",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":602},
            "size":{
              "width":282,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/对方空间（未付费）/u39_line.png"}},
{
          "id":"a68ae7ca1b6645cdb63ab7c2c05499bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":620},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2918bb9f0be54df592b6ab1f6065b51e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":620},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b633dd88ba6b46429827e089b014a533",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":660},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ba5ccd81a384fd797a401fdc349a5bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":660},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9ba8f33bb544c11bc84fe41e0c27bb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":660},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98252a56c13946b19f738c5e854413ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":660},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4404c23195c14b12b4da58ff2b3a2715",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":620},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc030edbde5740629718abe3c919e1e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":620},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e18da145d084c9b87efaeea43eb5d0e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":642},
            "size":{
              "width":282,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/对方空间（未付费）/u39_line.png"}},
{
          "id":"b8d7e44bcdfa4ffc999e1e6ecab12c38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":133,
              "y":125},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7675aabb76344dea0aaf45123891aa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":133,
                  "y":125},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd196d1767d042e6a6b022e0a1a12558",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":323,
              "y":74},
            "size":{
              "width":45,
              "height":45},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f01cfefb8f7f447bbc4afdc9c13d9a72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":323,
                  "y":74},
                "size":{
                  "width":45,
                  "height":45},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间（未付费）/u73.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f9d79bf294ef4046a294cb29d331c973":{
      "scriptId":"u0"},
    "89b6f2f0934f4fee9b8257226f80f03e":{
      "scriptId":"u1"},
    "8047921c459b4b44b3674710eb1efee3":{
      "scriptId":"u2"},
    "6c92b17edb804218a47cdb279e838ec2":{
      "scriptId":"u3"},
    "f002c26d48ac403587e35a2a81866565":{
      "scriptId":"u4"},
    "4bf39f00ab0a407f9d763c599d608f38":{
      "scriptId":"u5"},
    "b2a58fc9d35943ff8a7a8cb7613a57f6":{
      "scriptId":"u6"},
    "2a414ea515a640eabef6623aba767827":{
      "scriptId":"u7"},
    "b293884b370745b5b705332906aaec90":{
      "scriptId":"u8"},
    "e05766f9cc554d51a6be250433f9465d":{
      "scriptId":"u9"},
    "b909ffc86a714681bb680b342df083f3":{
      "scriptId":"u10"},
    "e8ff40eee3294abfb3b740be67f27dfb":{
      "scriptId":"u11"},
    "ea3a87c53e6e4d46ac037c564fa681be":{
      "scriptId":"u12"},
    "1123efea69c246a7b79d694f7a0d04cd":{
      "scriptId":"u13"},
    "f4cecbb5e7d140cc8273e165ff8e503a":{
      "scriptId":"u14"},
    "9318137324e04d1cb13f33328fe0f74d":{
      "scriptId":"u15"},
    "3b52029d22cb42e28a0f10d840309543":{
      "scriptId":"u16"},
    "c4d6d63aa4bc499c9432b5df432c5b77":{
      "scriptId":"u17"},
    "8617a3dae13c499e8217fb0d2eb3f0e8":{
      "scriptId":"u18"},
    "6b9201bd897b43249726a46d12e10c82":{
      "scriptId":"u19"},
    "fd1430bc6d83443facf0c8b361cb60df":{
      "scriptId":"u20"},
    "f3c4913d891f47679ff27ff998a6cd78":{
      "scriptId":"u21"},
    "71ac2dcd536646e9b5f7d462e1d22128":{
      "scriptId":"u22"},
    "4fc650409e7142b2af83ea331bc8c5f4":{
      "scriptId":"u23"},
    "10c71f4637f0421a86e59a8d41309d64":{
      "scriptId":"u24"},
    "784c5409ee3848d5b7b9b5dff4d9dc97":{
      "scriptId":"u25"},
    "2bd46020ec26483d8ccf24cdc86225c6":{
      "scriptId":"u26"},
    "6b93f6b3249943f193578147d7eba4e3":{
      "scriptId":"u27"},
    "f94316ace9464c429eeb6d265a392f12":{
      "scriptId":"u28"},
    "5ff11944009348d6a54a7c35125d6044":{
      "scriptId":"u29"},
    "33bd99f381b44389b4a5f3af29c5a30f":{
      "scriptId":"u30"},
    "260a407b5d3a4e6b9160691fdfdc9314":{
      "scriptId":"u31"},
    "c0153e3a0c72415aa9e0ce83998561a2":{
      "scriptId":"u32"},
    "3448e0fdcd4947409972c00a5df3ec36":{
      "scriptId":"u33"},
    "ff578e6ece1d4acd83ff9c902760ab0b":{
      "scriptId":"u34"},
    "b791d2452a4c41e897a4e4bc89497111":{
      "scriptId":"u35"},
    "1f18b0792cec4477ba2395b3fde4f568":{
      "scriptId":"u36"},
    "3319d38cb5044df3acb04d5b58e80606":{
      "scriptId":"u37"},
    "71437eeb30264b87b2bd7b99343f248d":{
      "scriptId":"u38"},
    "99bd45118abf45aead1a9897d8a9c15b":{
      "scriptId":"u39"},
    "bf4443db79c047a493b1f9648801a611":{
      "scriptId":"u40"},
    "90d3f4e839c34a1f9c7f69e6d1f025cb":{
      "scriptId":"u41"},
    "8bb194b4d0b44c9991483cd528c81de8":{
      "scriptId":"u42"},
    "a741038f54c54b46b797cc9d86fb52f7":{
      "scriptId":"u43"},
    "57a6de4ada984b4fb209b4f4c92018b2":{
      "scriptId":"u44"},
    "911830eb8687407dbfb41f34635a787f":{
      "scriptId":"u45"},
    "118ea46ac06c46dda387e93cc0fad071":{
      "scriptId":"u46"},
    "a4f1db55d9474fb3bd5de4ca6730ad30":{
      "scriptId":"u47"},
    "4f713752e9ca45b18dd3538a14fd1492":{
      "scriptId":"u48"},
    "e137db9abee142ea9228af3473298b1c":{
      "scriptId":"u49"},
    "e4776acc29ee4a26becaa9385262bc70":{
      "scriptId":"u50"},
    "8ed96af05df94df8b54391455a9d0649":{
      "scriptId":"u51"},
    "c3b00cf402664e2abb94dca02a4df49b":{
      "scriptId":"u52"},
    "8237c6513b674e99a86834b0be785455":{
      "scriptId":"u53"},
    "d033d67cbf564b5d911e8bdc10f5ec4a":{
      "scriptId":"u54"},
    "de6eacced980435b876fef12b9f3926f":{
      "scriptId":"u55"},
    "4486aee23c3a4247abf9718cfc5939f1":{
      "scriptId":"u56"},
    "da3177abc3f3494a81efad014262c042":{
      "scriptId":"u57"},
    "d999e73c11464714b718515f8ee7a5e9":{
      "scriptId":"u58"},
    "0824df5d413b40a18f66b88196d93b26":{
      "scriptId":"u59"},
    "cd3cd87aa0c44d87843dc2a4949d43f8":{
      "scriptId":"u60"},
    "ee2213e8cbef4e3ab0ba47fb92ec4ece":{
      "scriptId":"u61"},
    "a68ae7ca1b6645cdb63ab7c2c05499bb":{
      "scriptId":"u62"},
    "2918bb9f0be54df592b6ab1f6065b51e":{
      "scriptId":"u63"},
    "b633dd88ba6b46429827e089b014a533":{
      "scriptId":"u64"},
    "1ba5ccd81a384fd797a401fdc349a5bf":{
      "scriptId":"u65"},
    "d9ba8f33bb544c11bc84fe41e0c27bb4":{
      "scriptId":"u66"},
    "98252a56c13946b19f738c5e854413ab":{
      "scriptId":"u67"},
    "4404c23195c14b12b4da58ff2b3a2715":{
      "scriptId":"u68"},
    "dc030edbde5740629718abe3c919e1e1":{
      "scriptId":"u69"},
    "0e18da145d084c9b87efaeea43eb5d0e":{
      "scriptId":"u70"},
    "b8d7e44bcdfa4ffc999e1e6ecab12c38":{
      "scriptId":"u71"},
    "a7675aabb76344dea0aaf45123891aa5":{
      "scriptId":"u72"},
    "bd196d1767d042e6a6b022e0a1a12558":{
      "scriptId":"u73"},
    "f01cfefb8f7f447bbc4afdc9c13d9a72":{
      "scriptId":"u74"}}});