$axure.loadCurrentPage({
  "url":"对方空间.html",
  "generationDate":new Date(1428682077870.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"702d35544aaa413d9d8433e21c6fca92",
    "type":"Axure:Page",
    "name":"对方空间",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5d44dd8b2a404fb1810e1eb697b3d0cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":20},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0396b3e717143c6a212c90a1c24bf99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":20},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u0.png"}},
{
          "id":"353e29e2a9d64e51bf91197d01882a68",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":64},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"097ed902076f4c68acabf08de40241d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":185.5,
              "y":32},
            "size":{
              "width":49,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b8c4c8e968a44e29717d2ff2e9c2351",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":185.5,
                  "y":32},
                "size":{
                  "width":49,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b849a5fda554432daef92b5576283f29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":38},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28e3dc36db364f61a55d95000bd9db17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":68,
                  "y":38},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"293774e811a1437489a3799f7daa3824",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":333,
              "y":38},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc27aad210ad44339e949ba1985e82e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":333,
                  "y":38},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a13683414564b83afe592dc2f1fdd53",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":84},
            "size":{
              "width":60,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0890c61718f4c9abdeb2398a9ef9583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":84},
                "size":{
                  "width":60,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间/u9.png"}},
{
          "id":"054cc9ffaec34da38c8db33f9e74e912",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":84},
            "size":{
              "width":60,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beefb524596b44e1bbbdbba4945a22ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":139,
                  "y":84},
                "size":{
                  "width":60,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间/u9.png"}},
{
          "id":"47c6838fd3ef436c9b98149c9d64c1fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":212,
              "y":84},
            "size":{
              "width":60,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"096d424ea5454e7fb64c9999df8e0e07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":212,
                  "y":84},
                "size":{
                  "width":60,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间/u9.png"}},
{
          "id":"5578be0c5d97428e8222d1e3c6e0e8b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":84},
            "size":{
              "width":60,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6a33000a3d548d6846ea59ec2c7db19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":84},
                "size":{
                  "width":60,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间/u9.png"}},
{
          "id":"1918ef183a004718b6e1fa66104f2fd8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":217},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"69cc85e640e74f0d9e00d240177bc5fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":154},
            "size":{
              "width":60,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"000b5db86d814a31b749bcc88f0baa47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":154},
                "size":{
                  "width":60,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间/u9.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5d44dd8b2a404fb1810e1eb697b3d0cf":{
      "scriptId":"u0"},
    "a0396b3e717143c6a212c90a1c24bf99":{
      "scriptId":"u1"},
    "353e29e2a9d64e51bf91197d01882a68":{
      "scriptId":"u2"},
    "097ed902076f4c68acabf08de40241d8":{
      "scriptId":"u3"},
    "3b8c4c8e968a44e29717d2ff2e9c2351":{
      "scriptId":"u4"},
    "b849a5fda554432daef92b5576283f29":{
      "scriptId":"u5"},
    "28e3dc36db364f61a55d95000bd9db17":{
      "scriptId":"u6"},
    "293774e811a1437489a3799f7daa3824":{
      "scriptId":"u7"},
    "dc27aad210ad44339e949ba1985e82e1":{
      "scriptId":"u8"},
    "3a13683414564b83afe592dc2f1fdd53":{
      "scriptId":"u9"},
    "e0890c61718f4c9abdeb2398a9ef9583":{
      "scriptId":"u10"},
    "054cc9ffaec34da38c8db33f9e74e912":{
      "scriptId":"u11"},
    "beefb524596b44e1bbbdbba4945a22ad":{
      "scriptId":"u12"},
    "47c6838fd3ef436c9b98149c9d64c1fb":{
      "scriptId":"u13"},
    "096d424ea5454e7fb64c9999df8e0e07":{
      "scriptId":"u14"},
    "5578be0c5d97428e8222d1e3c6e0e8b6":{
      "scriptId":"u15"},
    "c6a33000a3d548d6846ea59ec2c7db19":{
      "scriptId":"u16"},
    "1918ef183a004718b6e1fa66104f2fd8":{
      "scriptId":"u17"},
    "69cc85e640e74f0d9e00d240177bc5fd":{
      "scriptId":"u18"},
    "000b5db86d814a31b749bcc88f0baa47":{
      "scriptId":"u19"}}});