$axure.loadCurrentPage({
  "url":"艳遇.html",
  "generationDate":new Date(1429020441975.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bac5b3510c6644ba966be814d528c9c2",
    "type":"Axure:Page",
    "name":"艳遇",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7afa3ed140544cf29b0d999e01860a06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a8318c65ed54de1b38ff663c673b776",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u0.png"}},
{
          "id":"b3250fecc3404d2687aeffccdef667e5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":64},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"19b4cc02f54841e386864abcbbf1587a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":84},
            "size":{
              "width":100,
              "height":100},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fea73bb92ace46608b8521ddc7c2bcf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":84},
                "size":{
                  "width":100,
                  "height":100},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u3.png"}},
{
          "id":"535dde262d5f440093697aabd996cd21",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":34},
            "size":{
              "width":88,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 城市选择 淡入淡出 500 ms",
                      "objectsToFades":[{
                          "objectPath":["82401a31f92b4e26b1e20af0407c338a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"b200c733f38c4d7b9031668f7977217e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":84},
            "size":{
              "width":100,
              "height":100},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0967b3eb42714062833a1c5a2a0d2544",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":84},
                "size":{
                  "width":100,
                  "height":100},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u3.png"}},
{
          "id":"23fe867a71d640928e1d28a21773413e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":257,
              "y":84},
            "size":{
              "width":100,
              "height":100},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cd6cc43e73a4a06954fdca205183c3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":257,
                  "y":84},
                "size":{
                  "width":100,
                  "height":100},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u3.png"}},
{
          "id":"1b198c3ada744ad4b7092bb96c2ade56",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":194},
            "size":{
              "width":100,
              "height":100},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dc580c1eef14205b87973daa18306ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":194},
                "size":{
                  "width":100,
                  "height":100},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u3.png"}},
{
          "id":"4e4e720da31d48729da26e12cec345e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":194},
            "size":{
              "width":100,
              "height":100},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"720fe3d2485b407e95103573b3006854",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":194},
                "size":{
                  "width":100,
                  "height":100},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u3.png"}},
{
          "id":"8b1f1fa7d48d44fd9074525b4f278a3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":257,
              "y":194},
            "size":{
              "width":100,
              "height":100},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07e4fecadf2643a2becabbb443a2e097",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":257,
                  "y":194},
                "size":{
                  "width":100,
                  "height":100},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u3.png"}},
{
          "id":"bd1e290d9c1348c695799216e272f046",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":304},
            "size":{
              "width":100,
              "height":100},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a58c455abb6d4539b6060ed3a2693f1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":304},
                "size":{
                  "width":100,
                  "height":100},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u3.png"}},
{
          "id":"cb561f735a964d9a94a186e12ff2f2fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":304},
            "size":{
              "width":100,
              "height":100},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4d97dc2783d42b58cc49fcb061b1667",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":304},
                "size":{
                  "width":100,
                  "height":100},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u3.png"}},
{
          "id":"88ced9d02e6d4003b642976b36204e6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":304},
            "size":{
              "width":100,
              "height":100},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbc789d0954d4e94be4897c7b961e0a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":258,
                  "y":304},
                "size":{
                  "width":100,
                  "height":100},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u3.png"}},
{
          "id":"bcac98674ee94567b0860445cb578b00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":465},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3898967c3c4b4b8983243e853ac07836",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":465},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"1d008134bfcf4cb18276be8e8866ba73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db40233a646a4423896e65ae8d69d664",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"629a58cfbdb54476ac96ef513bda6d1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02e699d2ba4b45a3bf6a1c69211e59de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"a7733cbf300d4aafa8abfce7b6f9a3ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbf23079d4b143c18f16ab45f09d08fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}},
{
          "id":"7ecc586f3c5442b8aaf56f0249d4b392",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":180,
              "y":32},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d272061b1f4406b96760698737bee61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":180,
                  "y":32},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3484045554634ee6bf3f10a1f97611fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":414},
            "size":{
              "width":100,
              "height":48},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffabcad4f19746eb8790d883cdd431f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":414},
                "size":{
                  "width":100,
                  "height":48},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u32.png"}},
{
          "id":"9321ebcd19f540cf93675d3bbec91b32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":414},
            "size":{
              "width":100,
              "height":48},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b7d9f97c92546a0a9510d09b5051f6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":414},
                "size":{
                  "width":100,
                  "height":48},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u32.png"}},
{
          "id":"8658b1ba8e0f46b994282dab8e1ca070",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":414},
            "size":{
              "width":100,
              "height":48},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"869e3bb90f204af2a3b569dd70ca6e2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":258,
                  "y":414},
                "size":{
                  "width":100,
                  "height":48},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u32.png"}},
{
          "id":"ff21e394d1654d4aa3a68d808e1515bf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":456},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"846cffa9c4ed4e4f8f844be7a0cc8c31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":164},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad93a41134dd4094a65af3f4ba9eff8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":164},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u39.png"}},
{
          "id":"d843342de64b486fa7db1c5ebbbb8358",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":46,
              "y":167},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ae51ef36d224fad9452019e2c905cca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":46,
                  "y":167},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a61bfbccf9c549fa8d16d5afd05e336b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":115,
              "y":167},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f613dfd277245c683d67c81e3452312",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":115,
                  "y":167},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3becc159c2194b9bb956ebcd5f127ef5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":164},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64bea45a83f84ec0b98926a59fee91f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":164},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u39.png"}},
{
          "id":"21821d96dc614ae49b03f2c16ce84c33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":153,
              "y":167},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6febf1ac6e834f2b82301cec7279eb11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":153,
                  "y":167},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33a4aa27cfa24402986975dd7590816c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":225,
              "y":167},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"954f91d4ba5d44e48d5a9d5df507c487",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":225,
                  "y":167},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9548dde5c6104ff38ced2268aadc89f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":257,
              "y":164},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2011eece161643338c9ebd8566d2a688",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":257,
                  "y":164},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u39.png"}},
{
          "id":"ea613e7672d64ce4876561b8d837315a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":260,
              "y":167},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c065f5df4e69412eb8e0847454ea0ba0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":260,
                  "y":167},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0aa965157a524ba0bb5b039517bef1f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":332,
              "y":167},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c08829543614671868b6b1bd9cce710",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":332,
                  "y":167},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ef60c327a7746ed95daafbb08a64e58",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":274},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce95b4d501b9414d9ae661d47712c260",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":274},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u39.png"}},
{
          "id":"e5d3e1ad342340e8aa7e3abb7d98d7b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":47,
              "y":277},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fedc201568604b25a06780062d307eab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":47,
                  "y":277},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f14bb4b121544771a800ee71c70740cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":116,
              "y":277},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38ffd56c48b8493fbe05ed3621bfd9fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":116,
                  "y":277},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9943b9f1a0644f7966fe6e34119e1d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":274},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4e31326be104225bfba5bd53cc4ea91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":274},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u39.png"}},
{
          "id":"75169ef037904d18acdf8b629e30b67e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":154,
              "y":277},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53522e4640aa4bec927165957948fcc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":154,
                  "y":277},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f98116c4cd764c6bb0674dd1a75721c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":226,
              "y":277},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99d243f293424b3b99d2e3356951a856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":226,
                  "y":277},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1d9d36ef04f48709aa48eb63df27376",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":257,
              "y":274},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b10485cbc8934f53862ef42ea3dfc1ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":257,
                  "y":274},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u39.png"}},
{
          "id":"9f500f0b788345b6840b8196db702e15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":261,
              "y":277},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cae797be5d143e8bcc94ab815a3c666",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":261,
                  "y":277},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3c7eb36745f4697a3b88bd96ea9232d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":333,
              "y":277},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da2ff263a536495b89399b02cf464b3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":333,
                  "y":277},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e0ba85fed8348c99ed392cc8fa78fa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":384},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b94060b722a45e49342ced975b37869",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":384},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u39.png"}},
{
          "id":"2db8b45ea7114e7da4aa5aab5ec260c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":47,
              "y":387},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ffb02451acb412d8663a36a08556da2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":47,
                  "y":387},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e06ca2ce2e847b584ba2a5072b9a3be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":116,
              "y":387},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"098bc33496774627905238f3cb63c338",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":116,
                  "y":387},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcc484b91ee541a4865ea7b96c4ef983",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":384},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c9e2df11b9742b793e24e01e9e77eb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":384},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u39.png"}},
{
          "id":"b721c3a844ee41c9a19a6290d7e8e178",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":154,
              "y":387},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"950d6f76e97d43b3bae7049b17b35ec1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":154,
                  "y":387},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10100401166a4942a9954c50da0bddef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":226,
              "y":387},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a2dedf2c16d402caf7780f22412a67a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":226,
                  "y":387},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f94bb3faf4f4ae9af4a98f47f5088b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":384},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e341a68c5384bef8836920f131487ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":258,
                  "y":384},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u39.png"}},
{
          "id":"23d129b812334ed38929971f29a9cfac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":260,
              "y":387},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a09a9a319ae647338c5b7c2d4b17b90f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":260,
                  "y":387},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cfa52e0238146c0990faf8139c66353",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":333,
              "y":387},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e40219731d7a4bb9ae59fc9a501d741e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":333,
                  "y":387},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82401a31f92b4e26b1e20af0407c338a",
          "label":"城市选择",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":92,
              "y":150},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0eab4264706b4f1fa4f435795a49eb84",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"85c24942802743f9a7b00cc4c1e3f0b6",
                  "label":"",
                  "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0.5,
                      "y":10},
                    "size":{
                      "width":200,
                      "height":236}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ffcc78ecfb98450ab99720aa7e617dee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0.5,
                          "y":10},
                        "size":{
                          "width":200,
                          "height":236}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/艳遇/u94.png"}},
{
                  "id":"3e3da46f4fc84c31adaecff32d49171e",
                  "label":"",
                  "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":87,
                      "y":37},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"35df1476ca4646978cdf518a8efb056c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":87,
                          "y":37},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"61e1744587f0439b921178880fb2b801",
                  "label":"",
                  "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":86,
                      "y":65},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a6c22c70c50b4268822f2a25758665ba",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":86,
                          "y":65},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a31ff5bfbbc846ffac7043519c15285b",
                  "label":"",
                  "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":86,
                      "y":95},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"89af5f0865784a62ab3cdf69e7a4c67d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":86,
                          "y":95},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4b864712b9e04c1da1fa8bdb26f94035",
                  "label":"",
                  "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":86,
                      "y":121},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"01b095be35f34b6abc4d3641557eae0f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":86,
                          "y":121},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5a61a8c81ad14af49c9a53b794cf2e37",
                  "label":"",
                  "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":86,
                      "y":147},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"250e19e222f848d39ce33312ce03c3af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":86,
                          "y":147},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a42ee4aeb0704a3692fa4a3d707db1e2",
                  "label":"",
                  "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":86,
                      "y":173},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2bd8efff3c204519bfb94c6f9d6a9dd2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":86,
                          "y":173},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e00fac588de941c48a2406db9056d24c",
                  "label":"",
                  "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":85},
                    "size":{
                      "width":200,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/艳遇/u108_line.png"}},
{
                  "id":"94df5563687e4d38ae796fb23dc28e76",
                  "label":"",
                  "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0.5,
                      "y":108},
                    "size":{
                      "width":200,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/艳遇/u108_line.png"}},
{
                  "id":"068cc0ecdabb4c40b61d41bdbe5353ca",
                  "label":"",
                  "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                  "panelIndex":0,
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":50.5,
                      "y":213},
                    "size":{
                      "width":100,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"9c7f06d879b543878b7a26a72a2c438c",
                  "label":"",
                  "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":178.5,
                      "y":0},
                    "size":{
                      "width":30,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"64a0e06a888144559cb19e207aedce17",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"82401a31f92b4e26b1e20af0407c338a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":178.5,
                          "y":0},
                        "size":{
                          "width":30,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/主页面/u22.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"0e74610f157c407d86546f9148fae224",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":142,
              "y":346},
            "size":{
              "width":100,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 城市选择 淡入淡出 500 ms",
                      "objectsToFades":[{
                          "objectPath":["82401a31f92b4e26b1e20af0407c338a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"1cd4bf8d85a14b53b7ab7b7616471f63",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":150},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 城市选择 淡入淡出 500 ms",
                      "objectsToFades":[{
                          "objectPath":["82401a31f92b4e26b1e20af0407c338a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"8a801b80cc30493fbba842f15d64c925",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":466},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bdea93b384547259668da6ed15de0cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":466},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u22.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7afa3ed140544cf29b0d999e01860a06":{
      "scriptId":"u0"},
    "9a8318c65ed54de1b38ff663c673b776":{
      "scriptId":"u1"},
    "b3250fecc3404d2687aeffccdef667e5":{
      "scriptId":"u2"},
    "19b4cc02f54841e386864abcbbf1587a":{
      "scriptId":"u3"},
    "fea73bb92ace46608b8521ddc7c2bcf2":{
      "scriptId":"u4"},
    "535dde262d5f440093697aabd996cd21":{
      "scriptId":"u5"},
    "b200c733f38c4d7b9031668f7977217e":{
      "scriptId":"u6"},
    "0967b3eb42714062833a1c5a2a0d2544":{
      "scriptId":"u7"},
    "23fe867a71d640928e1d28a21773413e":{
      "scriptId":"u8"},
    "1cd6cc43e73a4a06954fdca205183c3f":{
      "scriptId":"u9"},
    "1b198c3ada744ad4b7092bb96c2ade56":{
      "scriptId":"u10"},
    "0dc580c1eef14205b87973daa18306ba":{
      "scriptId":"u11"},
    "4e4e720da31d48729da26e12cec345e9":{
      "scriptId":"u12"},
    "720fe3d2485b407e95103573b3006854":{
      "scriptId":"u13"},
    "8b1f1fa7d48d44fd9074525b4f278a3d":{
      "scriptId":"u14"},
    "07e4fecadf2643a2becabbb443a2e097":{
      "scriptId":"u15"},
    "bd1e290d9c1348c695799216e272f046":{
      "scriptId":"u16"},
    "a58c455abb6d4539b6060ed3a2693f1b":{
      "scriptId":"u17"},
    "cb561f735a964d9a94a186e12ff2f2fb":{
      "scriptId":"u18"},
    "e4d97dc2783d42b58cc49fcb061b1667":{
      "scriptId":"u19"},
    "88ced9d02e6d4003b642976b36204e6f":{
      "scriptId":"u20"},
    "bbc789d0954d4e94be4897c7b961e0a4":{
      "scriptId":"u21"},
    "bcac98674ee94567b0860445cb578b00":{
      "scriptId":"u22"},
    "3898967c3c4b4b8983243e853ac07836":{
      "scriptId":"u23"},
    "1d008134bfcf4cb18276be8e8866ba73":{
      "scriptId":"u24"},
    "db40233a646a4423896e65ae8d69d664":{
      "scriptId":"u25"},
    "629a58cfbdb54476ac96ef513bda6d1a":{
      "scriptId":"u26"},
    "02e699d2ba4b45a3bf6a1c69211e59de":{
      "scriptId":"u27"},
    "a7733cbf300d4aafa8abfce7b6f9a3ec":{
      "scriptId":"u28"},
    "dbf23079d4b143c18f16ab45f09d08fd":{
      "scriptId":"u29"},
    "7ecc586f3c5442b8aaf56f0249d4b392":{
      "scriptId":"u30"},
    "3d272061b1f4406b96760698737bee61":{
      "scriptId":"u31"},
    "3484045554634ee6bf3f10a1f97611fd":{
      "scriptId":"u32"},
    "ffabcad4f19746eb8790d883cdd431f5":{
      "scriptId":"u33"},
    "9321ebcd19f540cf93675d3bbec91b32":{
      "scriptId":"u34"},
    "2b7d9f97c92546a0a9510d09b5051f6b":{
      "scriptId":"u35"},
    "8658b1ba8e0f46b994282dab8e1ca070":{
      "scriptId":"u36"},
    "869e3bb90f204af2a3b569dd70ca6e2a":{
      "scriptId":"u37"},
    "ff21e394d1654d4aa3a68d808e1515bf":{
      "scriptId":"u38"},
    "846cffa9c4ed4e4f8f844be7a0cc8c31":{
      "scriptId":"u39"},
    "ad93a41134dd4094a65af3f4ba9eff8d":{
      "scriptId":"u40"},
    "d843342de64b486fa7db1c5ebbbb8358":{
      "scriptId":"u41"},
    "8ae51ef36d224fad9452019e2c905cca":{
      "scriptId":"u42"},
    "a61bfbccf9c549fa8d16d5afd05e336b":{
      "scriptId":"u43"},
    "5f613dfd277245c683d67c81e3452312":{
      "scriptId":"u44"},
    "3becc159c2194b9bb956ebcd5f127ef5":{
      "scriptId":"u45"},
    "64bea45a83f84ec0b98926a59fee91f0":{
      "scriptId":"u46"},
    "21821d96dc614ae49b03f2c16ce84c33":{
      "scriptId":"u47"},
    "6febf1ac6e834f2b82301cec7279eb11":{
      "scriptId":"u48"},
    "33a4aa27cfa24402986975dd7590816c":{
      "scriptId":"u49"},
    "954f91d4ba5d44e48d5a9d5df507c487":{
      "scriptId":"u50"},
    "9548dde5c6104ff38ced2268aadc89f4":{
      "scriptId":"u51"},
    "2011eece161643338c9ebd8566d2a688":{
      "scriptId":"u52"},
    "ea613e7672d64ce4876561b8d837315a":{
      "scriptId":"u53"},
    "c065f5df4e69412eb8e0847454ea0ba0":{
      "scriptId":"u54"},
    "0aa965157a524ba0bb5b039517bef1f6":{
      "scriptId":"u55"},
    "1c08829543614671868b6b1bd9cce710":{
      "scriptId":"u56"},
    "4ef60c327a7746ed95daafbb08a64e58":{
      "scriptId":"u57"},
    "ce95b4d501b9414d9ae661d47712c260":{
      "scriptId":"u58"},
    "e5d3e1ad342340e8aa7e3abb7d98d7b4":{
      "scriptId":"u59"},
    "fedc201568604b25a06780062d307eab":{
      "scriptId":"u60"},
    "f14bb4b121544771a800ee71c70740cd":{
      "scriptId":"u61"},
    "38ffd56c48b8493fbe05ed3621bfd9fb":{
      "scriptId":"u62"},
    "f9943b9f1a0644f7966fe6e34119e1d7":{
      "scriptId":"u63"},
    "d4e31326be104225bfba5bd53cc4ea91":{
      "scriptId":"u64"},
    "75169ef037904d18acdf8b629e30b67e":{
      "scriptId":"u65"},
    "53522e4640aa4bec927165957948fcc3":{
      "scriptId":"u66"},
    "f98116c4cd764c6bb0674dd1a75721c5":{
      "scriptId":"u67"},
    "99d243f293424b3b99d2e3356951a856":{
      "scriptId":"u68"},
    "e1d9d36ef04f48709aa48eb63df27376":{
      "scriptId":"u69"},
    "b10485cbc8934f53862ef42ea3dfc1ed":{
      "scriptId":"u70"},
    "9f500f0b788345b6840b8196db702e15":{
      "scriptId":"u71"},
    "7cae797be5d143e8bcc94ab815a3c666":{
      "scriptId":"u72"},
    "a3c7eb36745f4697a3b88bd96ea9232d":{
      "scriptId":"u73"},
    "da2ff263a536495b89399b02cf464b3b":{
      "scriptId":"u74"},
    "9e0ba85fed8348c99ed392cc8fa78fa8":{
      "scriptId":"u75"},
    "9b94060b722a45e49342ced975b37869":{
      "scriptId":"u76"},
    "2db8b45ea7114e7da4aa5aab5ec260c3":{
      "scriptId":"u77"},
    "9ffb02451acb412d8663a36a08556da2":{
      "scriptId":"u78"},
    "0e06ca2ce2e847b584ba2a5072b9a3be":{
      "scriptId":"u79"},
    "098bc33496774627905238f3cb63c338":{
      "scriptId":"u80"},
    "fcc484b91ee541a4865ea7b96c4ef983":{
      "scriptId":"u81"},
    "4c9e2df11b9742b793e24e01e9e77eb2":{
      "scriptId":"u82"},
    "b721c3a844ee41c9a19a6290d7e8e178":{
      "scriptId":"u83"},
    "950d6f76e97d43b3bae7049b17b35ec1":{
      "scriptId":"u84"},
    "10100401166a4942a9954c50da0bddef":{
      "scriptId":"u85"},
    "9a2dedf2c16d402caf7780f22412a67a":{
      "scriptId":"u86"},
    "8f94bb3faf4f4ae9af4a98f47f5088b9":{
      "scriptId":"u87"},
    "0e341a68c5384bef8836920f131487ed":{
      "scriptId":"u88"},
    "23d129b812334ed38929971f29a9cfac":{
      "scriptId":"u89"},
    "a09a9a319ae647338c5b7c2d4b17b90f":{
      "scriptId":"u90"},
    "3cfa52e0238146c0990faf8139c66353":{
      "scriptId":"u91"},
    "e40219731d7a4bb9ae59fc9a501d741e":{
      "scriptId":"u92"},
    "82401a31f92b4e26b1e20af0407c338a":{
      "scriptId":"u93"},
    "85c24942802743f9a7b00cc4c1e3f0b6":{
      "scriptId":"u94"},
    "ffcc78ecfb98450ab99720aa7e617dee":{
      "scriptId":"u95"},
    "3e3da46f4fc84c31adaecff32d49171e":{
      "scriptId":"u96"},
    "35df1476ca4646978cdf518a8efb056c":{
      "scriptId":"u97"},
    "61e1744587f0439b921178880fb2b801":{
      "scriptId":"u98"},
    "a6c22c70c50b4268822f2a25758665ba":{
      "scriptId":"u99"},
    "a31ff5bfbbc846ffac7043519c15285b":{
      "scriptId":"u100"},
    "89af5f0865784a62ab3cdf69e7a4c67d":{
      "scriptId":"u101"},
    "4b864712b9e04c1da1fa8bdb26f94035":{
      "scriptId":"u102"},
    "01b095be35f34b6abc4d3641557eae0f":{
      "scriptId":"u103"},
    "5a61a8c81ad14af49c9a53b794cf2e37":{
      "scriptId":"u104"},
    "250e19e222f848d39ce33312ce03c3af":{
      "scriptId":"u105"},
    "a42ee4aeb0704a3692fa4a3d707db1e2":{
      "scriptId":"u106"},
    "2bd8efff3c204519bfb94c6f9d6a9dd2":{
      "scriptId":"u107"},
    "e00fac588de941c48a2406db9056d24c":{
      "scriptId":"u108"},
    "94df5563687e4d38ae796fb23dc28e76":{
      "scriptId":"u109"},
    "068cc0ecdabb4c40b61d41bdbe5353ca":{
      "scriptId":"u110"},
    "9c7f06d879b543878b7a26a72a2c438c":{
      "scriptId":"u111"},
    "64a0e06a888144559cb19e207aedce17":{
      "scriptId":"u112"},
    "0e74610f157c407d86546f9148fae224":{
      "scriptId":"u113"},
    "1cd4bf8d85a14b53b7ab7b7616471f63":{
      "scriptId":"u114"},
    "8a801b80cc30493fbba842f15d64c925":{
      "scriptId":"u115"},
    "4bdea93b384547259668da6ed15de0cd":{
      "scriptId":"u116"}}});