$axure.loadCurrentPage({
  "url":"聊天页面（未付费）_1.html",
  "generationDate":new Date(1429020443163.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f064d1249f764aacb1408a56302b92ac",
    "type":"Axure:Page",
    "name":"聊天页面（未付费）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aa8f67bcd8c34c27a57bb20ce40e2d1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18afc7a13cb5499c9f0295c7522bc125",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u0.png"}},
{
          "id":"04071823531e4e2a99ccce6bf7ca63fe",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":64},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"92e5ecad50874928856dda6908e82bbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":180,
              "y":32},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c70944f8a4ad43d19b24c2561cde540f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":180,
                  "y":32},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bb22c0036df445f9f4076a637c95aa6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":38},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7780f0a452949529d21a87707631673",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":38},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"817e69fc9bf24a07ba2bc8c6c508381c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":180},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48d7aa595e72499ea8fa070333d3d524",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":180},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u7.png"}},
{
          "id":"e0e0089376dc49a0926086f8fbde7611",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":79},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be0b68b51bb14ab9ac6ce8b295581be1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":79},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b28fe423483434d8cc2fafa9970f56c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":182},
            "size":{
              "width":200,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d762c9a7d2184db08070f7554267acbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":182},
                "size":{
                  "width":200,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u11.png"}},
{
          "id":"ad75475e92834fadb6646aebc73a5ada",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":188},
            "size":{
              "width":195,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee23112d90b84700bb801edde7c3bd65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":188},
                "size":{
                  "width":195,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab78420c04454aca9e59ebe33a6830d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":238},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b794e6a5dca047ec83b3ceeda7b3c5bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":238},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u7.png"}},
{
          "id":"3fa8b7030be346159c3e76135689c8a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":240},
            "size":{
              "width":200,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79458464339242c78d720e3a2f75b8a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":240},
                "size":{
                  "width":200,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u11.png"}},
{
          "id":"546cb11d05d04e63b132a3e14d45986c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":246},
            "size":{
              "width":195,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebf4577aebb3478f9b8b7cdf37c3fcf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":246},
                "size":{
                  "width":195,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da205447cbe742e0aaa088bab92702f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":450},
            "size":{
              "width":299,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a6ff1c26b1d4825acce03b814309371",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":450},
                "size":{
                  "width":299,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u21.png"}},
{
          "id":"4fcb2ecb4efa410ea69f7404f439fac2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":102},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1ba66d3464e40b193c37c1f5bf3cf80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":102},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u7.png"}},
{
          "id":"1093aaa721af42f2bc20ba4d1ed2e582",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":102},
            "size":{
              "width":200,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"208dc98ee67d45a1b7d638da0fddef38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":102},
                "size":{
                  "width":200,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u11.png"}},
{
          "id":"a87fefbd92ef431ba5480e448b62a218",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":108},
            "size":{
              "width":185,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0c59c28cd9f4be9bcb4aa849c08e62d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":108},
                "size":{
                  "width":185,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a473fef0ec946dfa109fee3e7233784",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":158},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffa1c1d8252f46bab19071e3f44ff889",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":158},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "aa8f67bcd8c34c27a57bb20ce40e2d1b":{
      "scriptId":"u0"},
    "18afc7a13cb5499c9f0295c7522bc125":{
      "scriptId":"u1"},
    "04071823531e4e2a99ccce6bf7ca63fe":{
      "scriptId":"u2"},
    "92e5ecad50874928856dda6908e82bbf":{
      "scriptId":"u3"},
    "c70944f8a4ad43d19b24c2561cde540f":{
      "scriptId":"u4"},
    "2bb22c0036df445f9f4076a637c95aa6":{
      "scriptId":"u5"},
    "c7780f0a452949529d21a87707631673":{
      "scriptId":"u6"},
    "817e69fc9bf24a07ba2bc8c6c508381c":{
      "scriptId":"u7"},
    "48d7aa595e72499ea8fa070333d3d524":{
      "scriptId":"u8"},
    "e0e0089376dc49a0926086f8fbde7611":{
      "scriptId":"u9"},
    "be0b68b51bb14ab9ac6ce8b295581be1":{
      "scriptId":"u10"},
    "8b28fe423483434d8cc2fafa9970f56c":{
      "scriptId":"u11"},
    "d762c9a7d2184db08070f7554267acbb":{
      "scriptId":"u12"},
    "ad75475e92834fadb6646aebc73a5ada":{
      "scriptId":"u13"},
    "ee23112d90b84700bb801edde7c3bd65":{
      "scriptId":"u14"},
    "ab78420c04454aca9e59ebe33a6830d8":{
      "scriptId":"u15"},
    "b794e6a5dca047ec83b3ceeda7b3c5bd":{
      "scriptId":"u16"},
    "3fa8b7030be346159c3e76135689c8a7":{
      "scriptId":"u17"},
    "79458464339242c78d720e3a2f75b8a5":{
      "scriptId":"u18"},
    "546cb11d05d04e63b132a3e14d45986c":{
      "scriptId":"u19"},
    "ebf4577aebb3478f9b8b7cdf37c3fcf5":{
      "scriptId":"u20"},
    "da205447cbe742e0aaa088bab92702f2":{
      "scriptId":"u21"},
    "3a6ff1c26b1d4825acce03b814309371":{
      "scriptId":"u22"},
    "4fcb2ecb4efa410ea69f7404f439fac2":{
      "scriptId":"u23"},
    "f1ba66d3464e40b193c37c1f5bf3cf80":{
      "scriptId":"u24"},
    "1093aaa721af42f2bc20ba4d1ed2e582":{
      "scriptId":"u25"},
    "208dc98ee67d45a1b7d638da0fddef38":{
      "scriptId":"u26"},
    "a87fefbd92ef431ba5480e448b62a218":{
      "scriptId":"u27"},
    "b0c59c28cd9f4be9bcb4aa849c08e62d":{
      "scriptId":"u28"},
    "5a473fef0ec946dfa109fee3e7233784":{
      "scriptId":"u29"},
    "ffa1c1d8252f46bab19071e3f44ff889":{
      "scriptId":"u30"}}});