$axure.loadCurrentPage({
  "url":"聊天页面（我已付费）.html",
  "generationDate":new Date(1429020442379),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ac3a3c640bb74eccbda64e4a61456125",
    "type":"Axure:Page",
    "name":"聊天页面（我已付费）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fc986d6cf2a54b8db87405f1c7c57bd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a1ca328f12841e5b993009e0b2cfba4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u0.png"}},
{
          "id":"aadaf4ae8ebf4a6f9237c60910c406af",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":64},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"3d9d1296fb6d44a393d22278f923f204",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":180,
              "y":32},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f081660c0a34167a2fa7326bb29787d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":180,
                  "y":32},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3d61d584b24444e9c8335510119aafa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":38},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe64cd3698e45e788e68357f03d3ff9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":38},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"648ec3455e744bb283f805f9f6cb41b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":103},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33cd3765c73749baa05be82941f06500",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":103},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u7.png"}},
{
          "id":"fdecf721314b475286133110aaa33fbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":84},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"993369a7f97e446999d8b145e71011c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":84},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0011f044e0c41e5abe3a68586183ed8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":105},
            "size":{
              "width":200,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32218fd0188340c8a40c62867a9e770b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":105},
                "size":{
                  "width":200,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u11.png"}},
{
          "id":"8556dd6aa982468b820a02a524f48b6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":111},
            "size":{
              "width":195,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7b4c88395e74282b236154966f0147d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":111},
                "size":{
                  "width":195,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99f5077904a94e79b752b55680aa0b6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":161},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf0b52dd3a5b4b5caff6e52c13d372d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":161},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u7.png"}},
{
          "id":"ccfda0b29f954e6b889549486544c8d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":163},
            "size":{
              "width":200,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"234cda076a93462cb645617d9689f60d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":163},
                "size":{
                  "width":200,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u11.png"}},
{
          "id":"b90c2ecbae414c699d153a29418e77a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":169},
            "size":{
              "width":195,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb367b19e03f47539bfd245c63ce9cae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":169},
                "size":{
                  "width":195,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd3a77bcdf624b2ebfcd0e899b89e697",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":460},
            "size":{
              "width":250,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a0c423412f442108ab20b075c6705cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":460},
                "size":{
                  "width":250,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（我已付费）/u21.png"}},
{
          "id":"54eacfdb8dc84a1cb35059140b1c8a20",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":462},
            "size":{
              "width":45,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "fc986d6cf2a54b8db87405f1c7c57bd5":{
      "scriptId":"u0"},
    "2a1ca328f12841e5b993009e0b2cfba4":{
      "scriptId":"u1"},
    "aadaf4ae8ebf4a6f9237c60910c406af":{
      "scriptId":"u2"},
    "3d9d1296fb6d44a393d22278f923f204":{
      "scriptId":"u3"},
    "9f081660c0a34167a2fa7326bb29787d":{
      "scriptId":"u4"},
    "d3d61d584b24444e9c8335510119aafa":{
      "scriptId":"u5"},
    "6fe64cd3698e45e788e68357f03d3ff9":{
      "scriptId":"u6"},
    "648ec3455e744bb283f805f9f6cb41b1":{
      "scriptId":"u7"},
    "33cd3765c73749baa05be82941f06500":{
      "scriptId":"u8"},
    "fdecf721314b475286133110aaa33fbb":{
      "scriptId":"u9"},
    "993369a7f97e446999d8b145e71011c6":{
      "scriptId":"u10"},
    "b0011f044e0c41e5abe3a68586183ed8":{
      "scriptId":"u11"},
    "32218fd0188340c8a40c62867a9e770b":{
      "scriptId":"u12"},
    "8556dd6aa982468b820a02a524f48b6b":{
      "scriptId":"u13"},
    "c7b4c88395e74282b236154966f0147d":{
      "scriptId":"u14"},
    "99f5077904a94e79b752b55680aa0b6f":{
      "scriptId":"u15"},
    "bf0b52dd3a5b4b5caff6e52c13d372d9":{
      "scriptId":"u16"},
    "ccfda0b29f954e6b889549486544c8d9":{
      "scriptId":"u17"},
    "234cda076a93462cb645617d9689f60d":{
      "scriptId":"u18"},
    "b90c2ecbae414c699d153a29418e77a9":{
      "scriptId":"u19"},
    "eb367b19e03f47539bfd245c63ce9cae":{
      "scriptId":"u20"},
    "dd3a77bcdf624b2ebfcd0e899b89e697":{
      "scriptId":"u21"},
    "7a0c423412f442108ab20b075c6705cd":{
      "scriptId":"u22"},
    "54eacfdb8dc84a1cb35059140b1c8a20":{
      "scriptId":"u23"}}});