$axure.loadCurrentPage({
  "url":"对方空间（未付费）.html",
  "generationDate":new Date(1429020442158.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"702d35544aaa413d9d8433e21c6fca92",
    "type":"Axure:Page",
    "name":"对方空间（未付费）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5d44dd8b2a404fb1810e1eb697b3d0cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":20},
            "size":{
              "width":320,
              "height":740}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0396b3e717143c6a212c90a1c24bf99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":20},
                "size":{
                  "width":320,
                  "height":740}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间（未付费）/u0.png"}},
{
          "id":"353e29e2a9d64e51bf91197d01882a68",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":64},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"097ed902076f4c68acabf08de40241d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":190,
              "y":32},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b8c4c8e968a44e29717d2ff2e9c2351",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":190,
                  "y":32},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b849a5fda554432daef92b5576283f29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":38},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28e3dc36db364f61a55d95000bd9db17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":68,
                  "y":38},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"293774e811a1437489a3799f7daa3824",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":333,
              "y":38},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc27aad210ad44339e949ba1985e82e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":333,
                  "y":38},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a13683414564b83afe592dc2f1fdd53",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":85},
            "size":{
              "width":60,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0890c61718f4c9abdeb2398a9ef9583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":85},
                "size":{
                  "width":60,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间（未付费）/u9.png"}},
{
          "id":"054cc9ffaec34da38c8db33f9e74e912",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":177},
            "size":{
              "width":60,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beefb524596b44e1bbbdbba4945a22ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":139,
                  "y":177},
                "size":{
                  "width":60,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间（未付费）/u9.png"}},
{
          "id":"47c6838fd3ef436c9b98149c9d64c1fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":212,
              "y":177},
            "size":{
              "width":60,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"096d424ea5454e7fb64c9999df8e0e07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":212,
                  "y":177},
                "size":{
                  "width":60,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间（未付费）/u9.png"}},
{
          "id":"5578be0c5d97428e8222d1e3c6e0e8b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":177},
            "size":{
              "width":60,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6a33000a3d548d6846ea59ec2c7db19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":177},
                "size":{
                  "width":60,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间（未付费）/u9.png"}},
{
          "id":"1918ef183a004718b6e1fa66104f2fd8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":155},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"69cc85e640e74f0d9e00d240177bc5fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":177},
            "size":{
              "width":60,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"000b5db86d814a31b749bcc88f0baa47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":177},
                "size":{
                  "width":60,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间（未付费）/u9.png"}},
{
          "id":"86efc92c7b1e4bc3b3888a63d32f4444",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":704},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"bbcfe5b740344dd99126acb0ff4feb43",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":709},
            "size":{
              "width":10,
              "height":50}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/对方空间（未付费）/u21_line.png"}},
{
          "id":"2044dc397b5c4042a8b2120e3d954ac7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":99,
              "y":726},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"141e82723bea42828fde75ec87ea8039",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":99,
                  "y":726},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"440e0199117b46c69649803b8669ddba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":263,
              "y":727},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"256b38a321f447be87212568f19055d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":263,
                  "y":727},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"731a05cc3eb3475c954e0d0f14a3bfe5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":265},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed30d779826f47e1a66edbd9f88c05b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":265},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"931e5bc012ab482d9c85c08d5dff8b31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":291},
            "size":{
              "width":282,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cc5971987fa4b80b7a3ba3bef5aedf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":291},
                "size":{
                  "width":282,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5892230596a349c192a02d7bfbb50b15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":454},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f34920a7d4b14ee6a729713bba841a19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":454},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69fcfffc11ee4be4b0fa2bfc14131ec6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":454},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ee2db6fdd82456d9cb9ed9f3473f1ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":454},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ce5c3ab995c4eeb91be20ae4f83f5d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":492},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48b14c758b394e63bccf970829757ecf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":492},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee8b347ad6724d18888568e342811c27",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":492},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f879485bd5974e94b186b31cb43e57d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":492},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d597adb76e64581b21928ddeb0c206b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":248},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"da3faff497464902810ef6ca185eb86d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":438},
            "size":{
              "width":282,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/对方空间（未付费）/u39_line.png"}},
{
          "id":"6771d70bab254439aa0941b31f98fd8c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":474},
            "size":{
              "width":282,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/对方空间（未付费）/u39_line.png"}},
{
          "id":"6f9b2164496c40389c66787a0d18f83d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":515},
            "size":{
              "width":282,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/对方空间（未付费）/u39_line.png"}},
{
          "id":"7c72be0d79df42d09c87b77147b91938",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":133,
              "y":87},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36827cdcb9c0494c89fc0a8a2270498a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":133,
                  "y":87},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"801f411a296541d5b44db517889cfe84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":183,
              "y":87},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a4133e8a1284959a22f22e792b92f77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":183,
                  "y":87},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99779efdd32b48e1b996ba86fffb600a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":234,
              "y":87},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75c99d3c0684434cad86304426b035fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":234,
                  "y":87},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d19d352b75ac4303957e89e77eabed9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":535},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42da1d5673ce402f8334b4a7894394d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":535},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec4d2d4fa7d84c7e91628e8eb4feb78b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":535},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a3261806719496eb5204c99d19089c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":535},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ec1a11a89284ddc9d7c7066bda05dac",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":558},
            "size":{
              "width":282,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/对方空间（未付费）/u39_line.png"}},
{
          "id":"c18158ba0f6e41b287c8a0c5a018ae73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":535},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5e28b5f9dd54b17ba3f42ba82b2ad3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":535},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb7fab0e7e594a6882e452765cea0596",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":536},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a41d86a5443f40c09bcdf59b6c32c29d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":536},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5c50c3f3cc14f48b34a36718fee8512",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":576},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2430ce96857347198613c03da09e0853",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":576},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ca147a243bb4f06b0fea35bd3f1823d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":576},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66713081ce7549a0a178e21cd4e19a4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":576},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d78aaca0b3814eab904ecf942b7cf27d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":602},
            "size":{
              "width":282,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/对方空间（未付费）/u39_line.png"}},
{
          "id":"7f1d20a74070426cb617679977845668",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":620},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f325e76ea66541a58610be9bc885027e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":620},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eeb8196cbdfe416bb91d6b0e76d3e486",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":660},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e77068ac41e424594f0b64294c10465",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":660},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc296ff56ad34d3282f991210fd5d9cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":660},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a2b0b897f544afe87887f4316738610",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":660},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"618acfc141da49368c5de7eb7bca1b03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":620},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa8f2711b5314ef998a557da5744fb3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":620},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f344c69b695a4dd5be58e1ad69754e4c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":642},
            "size":{
              "width":282,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/对方空间（未付费）/u39_line.png"}},
{
          "id":"9642fc0a0d8245b1b5258bc163613966",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":133,
              "y":125},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d82bd52dd204961b17440942dd213a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":133,
                  "y":125},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a586dd0fc1234b15b885072c2da27c5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":323,
              "y":74},
            "size":{
              "width":45,
              "height":45},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2672c559c64f4609a002f8ef5e117110",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":323,
                  "y":74},
                "size":{
                  "width":45,
                  "height":45},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对方空间（未付费）/u73.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5d44dd8b2a404fb1810e1eb697b3d0cf":{
      "scriptId":"u0"},
    "a0396b3e717143c6a212c90a1c24bf99":{
      "scriptId":"u1"},
    "353e29e2a9d64e51bf91197d01882a68":{
      "scriptId":"u2"},
    "097ed902076f4c68acabf08de40241d8":{
      "scriptId":"u3"},
    "3b8c4c8e968a44e29717d2ff2e9c2351":{
      "scriptId":"u4"},
    "b849a5fda554432daef92b5576283f29":{
      "scriptId":"u5"},
    "28e3dc36db364f61a55d95000bd9db17":{
      "scriptId":"u6"},
    "293774e811a1437489a3799f7daa3824":{
      "scriptId":"u7"},
    "dc27aad210ad44339e949ba1985e82e1":{
      "scriptId":"u8"},
    "3a13683414564b83afe592dc2f1fdd53":{
      "scriptId":"u9"},
    "e0890c61718f4c9abdeb2398a9ef9583":{
      "scriptId":"u10"},
    "054cc9ffaec34da38c8db33f9e74e912":{
      "scriptId":"u11"},
    "beefb524596b44e1bbbdbba4945a22ad":{
      "scriptId":"u12"},
    "47c6838fd3ef436c9b98149c9d64c1fb":{
      "scriptId":"u13"},
    "096d424ea5454e7fb64c9999df8e0e07":{
      "scriptId":"u14"},
    "5578be0c5d97428e8222d1e3c6e0e8b6":{
      "scriptId":"u15"},
    "c6a33000a3d548d6846ea59ec2c7db19":{
      "scriptId":"u16"},
    "1918ef183a004718b6e1fa66104f2fd8":{
      "scriptId":"u17"},
    "69cc85e640e74f0d9e00d240177bc5fd":{
      "scriptId":"u18"},
    "000b5db86d814a31b749bcc88f0baa47":{
      "scriptId":"u19"},
    "86efc92c7b1e4bc3b3888a63d32f4444":{
      "scriptId":"u20"},
    "bbcfe5b740344dd99126acb0ff4feb43":{
      "scriptId":"u21"},
    "2044dc397b5c4042a8b2120e3d954ac7":{
      "scriptId":"u22"},
    "141e82723bea42828fde75ec87ea8039":{
      "scriptId":"u23"},
    "440e0199117b46c69649803b8669ddba":{
      "scriptId":"u24"},
    "256b38a321f447be87212568f19055d9":{
      "scriptId":"u25"},
    "731a05cc3eb3475c954e0d0f14a3bfe5":{
      "scriptId":"u26"},
    "ed30d779826f47e1a66edbd9f88c05b4":{
      "scriptId":"u27"},
    "931e5bc012ab482d9c85c08d5dff8b31":{
      "scriptId":"u28"},
    "8cc5971987fa4b80b7a3ba3bef5aedf7":{
      "scriptId":"u29"},
    "5892230596a349c192a02d7bfbb50b15":{
      "scriptId":"u30"},
    "f34920a7d4b14ee6a729713bba841a19":{
      "scriptId":"u31"},
    "69fcfffc11ee4be4b0fa2bfc14131ec6":{
      "scriptId":"u32"},
    "3ee2db6fdd82456d9cb9ed9f3473f1ea":{
      "scriptId":"u33"},
    "6ce5c3ab995c4eeb91be20ae4f83f5d9":{
      "scriptId":"u34"},
    "48b14c758b394e63bccf970829757ecf":{
      "scriptId":"u35"},
    "ee8b347ad6724d18888568e342811c27":{
      "scriptId":"u36"},
    "f879485bd5974e94b186b31cb43e57d1":{
      "scriptId":"u37"},
    "2d597adb76e64581b21928ddeb0c206b":{
      "scriptId":"u38"},
    "da3faff497464902810ef6ca185eb86d":{
      "scriptId":"u39"},
    "6771d70bab254439aa0941b31f98fd8c":{
      "scriptId":"u40"},
    "6f9b2164496c40389c66787a0d18f83d":{
      "scriptId":"u41"},
    "7c72be0d79df42d09c87b77147b91938":{
      "scriptId":"u42"},
    "36827cdcb9c0494c89fc0a8a2270498a":{
      "scriptId":"u43"},
    "801f411a296541d5b44db517889cfe84":{
      "scriptId":"u44"},
    "1a4133e8a1284959a22f22e792b92f77":{
      "scriptId":"u45"},
    "99779efdd32b48e1b996ba86fffb600a":{
      "scriptId":"u46"},
    "75c99d3c0684434cad86304426b035fb":{
      "scriptId":"u47"},
    "d19d352b75ac4303957e89e77eabed9c":{
      "scriptId":"u48"},
    "42da1d5673ce402f8334b4a7894394d1":{
      "scriptId":"u49"},
    "ec4d2d4fa7d84c7e91628e8eb4feb78b":{
      "scriptId":"u50"},
    "2a3261806719496eb5204c99d19089c9":{
      "scriptId":"u51"},
    "5ec1a11a89284ddc9d7c7066bda05dac":{
      "scriptId":"u52"},
    "c18158ba0f6e41b287c8a0c5a018ae73":{
      "scriptId":"u53"},
    "b5e28b5f9dd54b17ba3f42ba82b2ad3e":{
      "scriptId":"u54"},
    "fb7fab0e7e594a6882e452765cea0596":{
      "scriptId":"u55"},
    "a41d86a5443f40c09bcdf59b6c32c29d":{
      "scriptId":"u56"},
    "e5c50c3f3cc14f48b34a36718fee8512":{
      "scriptId":"u57"},
    "2430ce96857347198613c03da09e0853":{
      "scriptId":"u58"},
    "0ca147a243bb4f06b0fea35bd3f1823d":{
      "scriptId":"u59"},
    "66713081ce7549a0a178e21cd4e19a4b":{
      "scriptId":"u60"},
    "d78aaca0b3814eab904ecf942b7cf27d":{
      "scriptId":"u61"},
    "7f1d20a74070426cb617679977845668":{
      "scriptId":"u62"},
    "f325e76ea66541a58610be9bc885027e":{
      "scriptId":"u63"},
    "eeb8196cbdfe416bb91d6b0e76d3e486":{
      "scriptId":"u64"},
    "0e77068ac41e424594f0b64294c10465":{
      "scriptId":"u65"},
    "bc296ff56ad34d3282f991210fd5d9cb":{
      "scriptId":"u66"},
    "5a2b0b897f544afe87887f4316738610":{
      "scriptId":"u67"},
    "618acfc141da49368c5de7eb7bca1b03":{
      "scriptId":"u68"},
    "fa8f2711b5314ef998a557da5744fb3f":{
      "scriptId":"u69"},
    "f344c69b695a4dd5be58e1ad69754e4c":{
      "scriptId":"u70"},
    "9642fc0a0d8245b1b5258bc163613966":{
      "scriptId":"u71"},
    "5d82bd52dd204961b17440942dd213a4":{
      "scriptId":"u72"},
    "a586dd0fc1234b15b885072c2da27c5e":{
      "scriptId":"u73"},
    "2672c559c64f4609a002f8ef5e117110":{
      "scriptId":"u74"}}});