$axure.loadCurrentPage({
  "url":"聊天页面（我已付费）_1.html",
  "generationDate":new Date(1429020443209.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"951e742f6ca74871aaeceb0e944335a4",
    "type":"Axure:Page",
    "name":"聊天页面（我已付费）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fe5b95aba640488bb19c7da166c5d349",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f84a093b29de4cb68d58ace30b2d4858",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u0.png"}},
{
          "id":"13939f7bc73145c8bd10f22bd4936d35",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":64},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"b71b686cba0441a8a5a90c4a42e0b3b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":180,
              "y":32},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"949821d2d9bc44e2b3c5506e79f155e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":180,
                  "y":32},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30db7d5e81ab465ba85fc7db872b9426",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":38},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"605a3b0a252a47188055f9fa935c6976",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":38},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c12fb1ed0714744a7c9304010d6134d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":103},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7af9b66223b427eb1ca615a3d172ce6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":103},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u7.png"}},
{
          "id":"cfc3a6e501ea432eadfda649f7132e82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":84},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"261ad8f2d1c14a67878efe8d5df4345b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":84},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d53e59823155489aace2b961725b9580",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":105},
            "size":{
              "width":205,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0160991b81724f52aeca31757dbda2f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":105},
                "size":{
                  "width":205,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（我已付费）_1/u11.png"}},
{
          "id":"d19e2ca56527411c9c831afe5fb0254f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":111},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5e40746f7a2497cadf53a85abdd6d3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":111},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0eb7e666313437f9058b8ba227cb98c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":460},
            "size":{
              "width":250,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f93ad5b059e7488eaf29871a04395348",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":460},
                "size":{
                  "width":250,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（我已付费）/u21.png"}},
{
          "id":"d39c5209ae8148d8ac98724df7322ed4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":462},
            "size":{
              "width":45,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "fe5b95aba640488bb19c7da166c5d349":{
      "scriptId":"u0"},
    "f84a093b29de4cb68d58ace30b2d4858":{
      "scriptId":"u1"},
    "13939f7bc73145c8bd10f22bd4936d35":{
      "scriptId":"u2"},
    "b71b686cba0441a8a5a90c4a42e0b3b7":{
      "scriptId":"u3"},
    "949821d2d9bc44e2b3c5506e79f155e9":{
      "scriptId":"u4"},
    "30db7d5e81ab465ba85fc7db872b9426":{
      "scriptId":"u5"},
    "605a3b0a252a47188055f9fa935c6976":{
      "scriptId":"u6"},
    "8c12fb1ed0714744a7c9304010d6134d":{
      "scriptId":"u7"},
    "f7af9b66223b427eb1ca615a3d172ce6":{
      "scriptId":"u8"},
    "cfc3a6e501ea432eadfda649f7132e82":{
      "scriptId":"u9"},
    "261ad8f2d1c14a67878efe8d5df4345b":{
      "scriptId":"u10"},
    "d53e59823155489aace2b961725b9580":{
      "scriptId":"u11"},
    "0160991b81724f52aeca31757dbda2f2":{
      "scriptId":"u12"},
    "d19e2ca56527411c9c831afe5fb0254f":{
      "scriptId":"u13"},
    "d5e40746f7a2497cadf53a85abdd6d3c":{
      "scriptId":"u14"},
    "b0eb7e666313437f9058b8ba227cb98c":{
      "scriptId":"u15"},
    "f93ad5b059e7488eaf29871a04395348":{
      "scriptId":"u16"},
    "d39c5209ae8148d8ac98724df7322ed4":{
      "scriptId":"u17"}}});