$axure.loadCurrentPage({
  "url":"聊天页面（未付费）.html",
  "generationDate":new Date(1429020442333),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4f707eb1d26f4d98aae074b136c3d744",
    "type":"Axure:Page",
    "name":"聊天页面（未付费）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"eeafa3e9155e414a9219b1261749a8f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dd880eecf9f4e75889826731bb24a96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u0.png"}},
{
          "id":"3c017a27026a4e748aa7fd58e14648cb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":64},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页面/u2_line.png"}},
{
          "id":"f037b3fcf7f44615a557e8a51cf49584",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":179.5,
              "y":32},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0dbc99536b943108aa34c741c049fc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":179.5,
                  "y":32},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd5e7a876ac5413c9803b6c1f27b8243",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":38},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34aee641e47040f08affd5ea495db0e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":38},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92bb96787c284f95a0ff0ccf704a74d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":103},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"148b84d144e946bf8f9983a2e26cd81b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":103},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u7.png"}},
{
          "id":"5b5a3ee278c747b0b8f9f5394eebf30c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":84},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6396f6cc56f4256a0ddc16597457c90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":84},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2cdb5d652698491d980c494b23fd6a20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":105},
            "size":{
              "width":200,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"073ebf7d88d04383a6684ff05875532c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":105},
                "size":{
                  "width":200,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u11.png"}},
{
          "id":"6d9e79eadcb64de98ed628c6a971f514",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":111},
            "size":{
              "width":195,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79945c64fc8240e192a9d1076286c628",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":111},
                "size":{
                  "width":195,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5684cfeb944400996319cfd8742bf71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":161},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4346951f5a2949c08cb3d41d9fbf1e70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":161},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u7.png"}},
{
          "id":"cb06709e0ca14d7a803018b3f9f94b62",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":163},
            "size":{
              "width":200,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"753ef827dcef45d79034e26360765ce8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":163},
                "size":{
                  "width":200,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u11.png"}},
{
          "id":"28e9647dc6524d35bcd0c981e86f6803",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":169},
            "size":{
              "width":195,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6f069f8730f4a5d94a25e8b722b97fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":169},
                "size":{
                  "width":195,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"124643016a234d53bfa34b3a0b252b94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":450},
            "size":{
              "width":299,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0114b3c48b3f4c4db8c23f06df0049c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":450},
                "size":{
                  "width":299,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天页面（未付费）/u21.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "eeafa3e9155e414a9219b1261749a8f1":{
      "scriptId":"u0"},
    "7dd880eecf9f4e75889826731bb24a96":{
      "scriptId":"u1"},
    "3c017a27026a4e748aa7fd58e14648cb":{
      "scriptId":"u2"},
    "f037b3fcf7f44615a557e8a51cf49584":{
      "scriptId":"u3"},
    "b0dbc99536b943108aa34c741c049fc3":{
      "scriptId":"u4"},
    "dd5e7a876ac5413c9803b6c1f27b8243":{
      "scriptId":"u5"},
    "34aee641e47040f08affd5ea495db0e4":{
      "scriptId":"u6"},
    "92bb96787c284f95a0ff0ccf704a74d5":{
      "scriptId":"u7"},
    "148b84d144e946bf8f9983a2e26cd81b":{
      "scriptId":"u8"},
    "5b5a3ee278c747b0b8f9f5394eebf30c":{
      "scriptId":"u9"},
    "d6396f6cc56f4256a0ddc16597457c90":{
      "scriptId":"u10"},
    "2cdb5d652698491d980c494b23fd6a20":{
      "scriptId":"u11"},
    "073ebf7d88d04383a6684ff05875532c":{
      "scriptId":"u12"},
    "6d9e79eadcb64de98ed628c6a971f514":{
      "scriptId":"u13"},
    "79945c64fc8240e192a9d1076286c628":{
      "scriptId":"u14"},
    "d5684cfeb944400996319cfd8742bf71":{
      "scriptId":"u15"},
    "4346951f5a2949c08cb3d41d9fbf1e70":{
      "scriptId":"u16"},
    "cb06709e0ca14d7a803018b3f9f94b62":{
      "scriptId":"u17"},
    "753ef827dcef45d79034e26360765ce8":{
      "scriptId":"u18"},
    "28e9647dc6524d35bcd0c981e86f6803":{
      "scriptId":"u19"},
    "d6f069f8730f4a5d94a25e8b722b97fc":{
      "scriptId":"u20"},
    "124643016a234d53bfa34b3a0b252b94":{
      "scriptId":"u21"},
    "0114b3c48b3f4c4db8c23f06df0049c3":{
      "scriptId":"u22"}}});